#!/bin/bash
# MICA reface
#
#
# Class: Optional pre processing step (ANONYMIZE)
# we strongly recommend to anonymize the BIDS database before running MICAPIPE
#
#
# Rationale: This script applies a defacing/refacing/warp-refacing to anonymize the anatomical images in a BIDS dataset.
#            A warp field is calculated from the anatomical image (eg. T1w, qT1, FLAIR...) to the refaced T1w.
#            The resulting warp fields are then applied to each anamical image to anonymize the face
#
#
#
# source print funtions for MICAPIPE
MICAPIPE=$(dirname $(dirname $(realpath "$0")))
source "${MICAPIPE}/functions/utilities.sh"

help() {
echo -e "
\033[38;5;141mCOMMAND:\033[0m
   $(basename $0)

\033[38;5;141mARGUMENTS:\033[0m
\t\033[38;5;197m-sub\033[0m 	        : Subject identification (no 'sub-')
\t\033[38;5;197m-out\033[0m      	: Output directory for the processed files <anat ORIG and face-warps>.
\t\033[38;5;197m-bids\033[0m      	: Path to BIDS directory
\t\033[38;5;120m-ses\033[0m 	        : OPTIONAL flag that indicates the session name (if omitted will manage as SINGLE session)

   Methods:
\t\033[38;5;197m-warpface\033[0m 	: Method to anonymize the anat images by creating a new Warped-face
\t\033[38;5;197m-reface\033[0m 	: Method to anonymize the anat images by creating a new face
\t\033[38;5;197m-deface\033[0m 	: Method to anonymize the anat images by erasing the face
\t\033[38;5;197m-all\033[0m 	        : Runs all the previous algorithms

\033[38;5;141mOPTIONAL ARGUMENTS:\033[0m
\t\033[38;5;120m-T1\033[0m        : Path to manually identify the main scan for registration (ONE, e.g. '-T1 ./sub-1/anat/sub-1_T1w.nii.gz').
\t\033[38;5;197m-dilate\033[0m 	  : Dilation of the refaced mask (default is 6, set higher if the brain is cropped)
\t\033[38;5;197m-robust\033[0m 	  : If reface-warped isn't great, TRY this option to run a ROBUST registration (More computation time)
\t\033[38;5;120m-regSynth\033[0m  : Specify this option to perform the registration based on synthseg.
\t\033[38;5;197m-nocleanup\033[0m : Do NOT DELETE temporal directory at script completion.
\t\033[38;5;197m-threads\033[0m   : Number of threads (Default is 6)

\033[38;5;141mUSAGE:\033[0m
\033[38;5;141m$(basename $0)\033[0m  \033[38;5;197m-sub\033[0m <subject_id> \033[38;5;197m-out\033[0m <outputDirectory> \033[38;5;197m-bids\033[0m <BIDS-directory>\n \033[38;5;197m-all\033[0m

\033[38;5;141mDEPENDENCIES:\033[0m
    > ANTs        2.3.4   (https://github.com/ANTsX/ANTs)
    > FSL         6.0     (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki)
    > AFNI        20.3.03 (https://afni.nimh.nih.gov/download)

\033[38;5;141mWARNING:\033[0m ANONYMIZEs the anatomical images from the BIDS directory
             The anonimized images will be saved in the OUT directory
             Is up to the user to replace the BIDS anatomical by the outputs of this script
             We strongly recomend that the OUT directory is not the BIDS nor the DERIVATIVES


RRC
McGill University, MNI, MICA-lab, Novemeber 2020
https://github.com/MICA-MNI
http://mica-mni.github.io/
"
}

# -----------------------------------------------------------------------------------------------#
#			ARGUMENTS
# Create VARIABLES
for arg in "$@"
do
  case "$arg" in
  -h|-help)
    help
    exit 1
  ;;
  -sub)
    id=$2
    shift;shift
  ;;
  -out)
    out=$2
    shift;shift
  ;;
  -bids)
    BIDS=$2
    shift;shift
  ;;
  -ses)
    SES=$2
    shift;shift
  ;;
  -reface)
    METHOD="reface"
    shift
  ;;
  -warpface)
    METHOD="warpface"
    shift
  ;;
  -all)
    METHOD="all"
    shift
  ;;
  -deface)
    METHOD="deface"
    shift
  ;;
  -dilate)
    dil=$2
    shift;shift
  ;;
  -robust)
    robust=TRUE
    shift
  ;;
  -regSynth)
    synth_reg=TRUE
    shift
  ;;
  -T1)
    T1w="$2"
    shift;shift;s
  ;;
  -threads)
    threads=$2
    shift;shift
  ;;
  -nocleanup)
    nocleanup=TRUE
    shift
  ;;
  -*)
    Error "Unknown option ${2}"
    help
    exit
  ;;
    esac
done

# argument check out & WARNINGS
missing_arg

# Define the method
if [ -z ${METHOD} ]; then Error "The method is missing, add a flag: -deface, -reface -warpface or -all"; help; exit; fi

# Get the real path of the Inputs
out=$(realpath $out)
BIDS=$(realpath $BIDS)
id=${id/sub-/}

# Number of session (Default is "ses-pre")
if [ -z ${SES} ]; then SES="ses-pre"; else SES="ses-${SES/ses-/}"; fi

# Dilate (Default is 6)
if [ -z ${dil} ]; then dil=6; fi

# THREADS should be defined as GLOBAL variable maybe
if [[ -z $threads ]]; then export threads=6; Info "ANTs will use $threads threads"; fi

# sythreg based registration
if [[ ${synth_reg} == "TRUE" ]]; then synth_reg=${synth_reg}; else synth_reg="FALSE"; fi

# Assigns BIDS variables names
bids_variables $BIDS $id $out $SES

# Check BIDS directory
if [ ! -d ${subject_bids} ]; then Error "$id was not found on the BIDS directory\n\t     ${subject_bids}"; exit 0; fi

# -----------------------------------------------------------------------------------------------#
# Assign variables from template directory
mics_t1=$util_mics/MICs60_T1_0.8mm.nii.gz
mics_t1_ROI=$util_mics/MICs60_T1_0.8mm_mask-defaceROI.nii.gz
mics_t1_face=$util_mics/MICs60_T1_0.8mm_face.nii.gz
mics_t1_brainNeck=$util_mics/MICs60_T1_0.8mm_mask-brainNeck.nii.gz
mics_t1_synth=$util_mics/MICs60_T1_0.8mm_synthseg.nii.gz
here=$(pwd)

# -----------------------------------------------------------------------------------------------#
# Assign variables from BIDS directory
bids_T1ws=($(ls "$subject_bids"/anat/*T1w.nii* 2>/dev/null))

# Get the T1w_run-1 name (no path). Note bids_T1ws come from bids_variables
T1w_run1="${bids_T1ws[0]#*anat/}"

# Go to BIDS/anat to create a list of all the Volumes
cd "${subject_bids}/anat" || exit 1

# Collect anatomical volumes and specific T1map-related files
shopt -s nullglob
anat=(*.nii.gz)
mapfile -t anatT1map < <(find . -name "*T1map.nii.gz" ! -name "T1map.nii.gz")
mapfile -t T1map_inv1 < <(find . -name "*inv1_T1map.nii.gz")
T1map_inv1=("${T1map_inv1[@]#./}")

# Filter deface/reface/warpface BEFORE any logic that depends on these arrays
if [ "${#anatT1map[@]}" -gt 0 ]; then
  mapfile -t anatT1map < <( printf '%s\n' "${anatT1map[@]}" | grep -Ev 'rec-(deface|reface|warpface)')
else
  anatT1map=()
fi
if [ "${#anat[@]}" -gt 0 ]; then
  mapfile -t anat < <( printf '%s\n' "${anat[@]}" | grep -Ev 'rec-(deface|reface|warpface)')
else
  anat=()
fi

# If ALL niftis were de-identified, nothing remains to process: exit early
all_niftis=(*.nii.gz)
if [ "${#all_niftis[@]}" -gt 0 ] && [ "${#anat[@]}" -eq 0 ] && [ "${#anatT1map[@]}" -eq 0 ]; then
  Info "sub-${subject} | All the files seem to have been de-identified:"
  for file in "${subject_bids}/anat/"*nii*; do f=$(basename "${file}"); echo -e "\t\t${f}"; done
  exit 0
fi

# Derive T1w_run1: user-provided > run-1 > any T1w > MP2RAGE inv-1
if [ -n "${T1w}" ]; then
  T1_orig=$(realpath "${T1w}")
else
  T1_orig=$(printf '%s\n' "${anat[@]}" | grep 'run-1_T1w\|T1w' | head -1)
  T1_orig="${subject_bids}/anat/${T1_orig}"
fi

# Fallback to MP2RAGE inv-1 if still missing
if [ ! -f "${T1_orig}" ]; then
  Warning "T1w image not found, trying to use MP2RAGE as reference"
  T1_orig=$(ls "${subject_bids}/anat/"*_inv-1_MP2RAGE.nii.gz 2>/dev/null | head -1)
fi

# Abort if no reference found
if [ ! -f "${T1_orig}" ]; then
  Error "T1w image not found and no MP2RAGE inv-1 available: try -T1" " 2"
  for file in "${subject_bids}/anat/"*nii*; do echo -e "\t\t$(basename "${file}")"; done
  exit 2
fi

# Derive T1w_run1 and T1w_run1_str from final T1_orig
T1w_run1=$(basename "${T1_orig}")
T1w_run1_str="${T1w_run1%.nii.gz}"
Info "T1w reference: ${T1w_run1}"

# Creates OUT directory if it doesn't exist
out_warps=${out}/${subject}/${SES}/anat
if [ ! -d ${out_warps} ]; then Do_cmd mkdir -p ${out_warps}; fi

#------------------------------------------------------------------------------#
Title "Running MICA-anonymize"

# if temporary directory is empty
if [ -z ${TMPDIR} ]; then TMPDIR=/tmp; fi

Note "Reference MRI:" "${T1w_run1_str}"
Note "Method:" "\t${METHOD}"
Note "Threads:" "${threads}"
Note "RegSynth:" "${synth_reg}"
Note "Output:" "$out_warps"
Note "TMPDIR:" "${TMPDIR}"


Info "T1w to register: $T1w_run1\n\t\tOther anatomical volumes:"
for i in ${anat[@]}; do echo -e "\t\t$i"; done
if [ "${#anatT1map[@]}" -gt 0 ] && [ -n "${anatT1map[*]}" ]; then
  Info "T1map to register: $T1map_inv1\n\t\tOther T1map volumes:"
  for i in ${anatT1map[@]}; do echo -e "\t\t$i"; done
fi

Warning "This script de-identifies anatomical images from a BIDS directory.
\t\tThe processed images are written to the OUT directory and include
\t\tthe tag: rec-<method:{deface,reface,warpface}> in their filenames.

\t\tThe user is responsible for replacing the original BIDS anatomical
\t\timages with the de-identified versions if desired.

\t\tIf the OUT directory is the same as the BIDS directory, the user
\t\tmust move or back up the original non-de-identified data before
\t\tsharing to avoid accidental disclosure."

# Timer & Beginning
aloita=$(date +%s)

# Create temporal directory
tmp=${TMPDIR}/${RANDOM}_micapipe_anonymize_${id}
if [ ! -d $tmp ]; then Do_cmd mkdir -p $tmp; fi

# move to tmp directory
Do_cmd cd $tmp

# TRAP in case the script fails
trap 'cleanup $tmp $nocleanup $here' SIGINT SIGTERM

# -----------------------------------------------------------------------------------------------
# Affine registration from NATIVE REFERENCE to MICs60_T1w-atlas
T1w_run1_str=${T1w_run1/.nii.gz/}
T1w_2_MICs=${tmp}/T1w_2_MICs60
T1w_2_mics_mat=${T1w_2_MICs}_0GenericAffine.mat
if [[ "${synth_reg}" == "TRUE" ]]; then
  Info "Running label based affine registrations"
  micst1_synth="${tmp}/micst1_synthsegGM.nii.gz"
  T1_synth="${tmp}/T1w_synthsegGM.nii.gz"
  Do_cmd mri_synthseg --i "${T1_orig}" --o "${tmp}/T1w_synthseg.nii.gz" --robust --threads $threads --cpu
  Do_cmd fslmaths "${tmp}/T1w_synthseg.nii.gz" -uthr 42 -thr 42 -bin -mul -39 -add "${tmp}/T1w_synthseg.nii.gz" "${T1_synth}"

  Do_cmd fslmaths "${mics_t1_synth}" -uthr 42 -thr 42 -bin -mul -39 -add "${mics_t1_synth}" "${micst1_synth}"

  # Affine from func to t1-nativepro
  Do_cmd antsRegistrationSyN.sh -d 3 -f $micst1_synth -m $T1_synth -o ${T1w_2_MICs}_ -t a -n $threads -p f
else
  Info "Running volume based affine registrations"
  Do_cmd antsRegistrationSyN.sh -d 3 -f $mics_t1 -m $T1_orig -o ${T1w_2_MICs}_ -t a -n $threads -p f
fi

if [ ! -f ${T1w_2_mics_mat} ]; then Error "Affine registration failed"; cd $here;  Do_cmd exit 0; fi

# -----------------------------------------------------------------------------------------------
# DE-IDENTIFIES NAMING
# Based on neurostars discussion: 
#  > https://neurostars.org/t/use-of-defaced-t1w-in-fmriprep-how-to-organise-data/32333/2
# Use rec-${method} to identify the algorithm used in the de-identification. It should follow the BIDS hierarchy:
# sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>][_chunk-<index>]_<SUFFIX>.nii[.gz]

# -----------------------------------------------------------------------------------------------
# JSON de-identified
# remove keys:  ProcedureStepDescription
# ADD: "RawImage": false, "DeIdentified": $METHOD
json_deidentify() {
    local json_orig="$1"
    local json_deid="$2"
    local json_method="$3"

    # Guard: skip if source json does not exist
    if [ ! -f "${json_orig}" ]; then
      Warning "JSON not found, skipping: ${json_orig}"
      return 0
    fi

    cp "${json_orig}" "${json_deid}"
    jq --arg method "${json_method}" \
      'del(
        .AcquisitionComments,
        .AcquisitionContextSequence,
        .AcquisitionDate,
        .AcquisitionDateTime,
        .AcquisitionDeviceProcessingDescription,
        .AcquisitionProtocolDescription
      )
      + {
        "RawImage": false,
        "DeidentificationMethod": [$method]
      }' \
      "${json_deid}" > "${json_deid}.tmp" && mv "${json_deid}.tmp" "${json_deid}"
}

# -----------------------------------------------------------------------------------------------
# DEFACE
if [ "$METHOD" == "deface" ] || [ "$METHOD" = "all" ]; then

    Note "Calculating parameters:" "deface"
    roi_deface_T1w=${T1w_2_MICs}_defaceROI.nii.gz
    defaced=$(bids_add_rec ${out_warps}/${T1w_run1_str}.nii.gz $METHOD)

    # Apply face ROI to native T1w volume
    Do_cmd antsApplyTransforms -d 3 -u int -i $mics_t1_ROI -r $T1_orig -n GenericLabel -t [${T1w_2_mics_mat},1] -o $roi_deface_T1w
    Do_cmd fslmaths $roi_deface_T1w -binv -mul $T1_orig $defaced
fi

# -----------------------------------------------------------------------------------------------
# REFACE
if [ "$METHOD" == "reface" ] || [ "$METHOD" = "warpface" ] || [ "$METHOD" = "all" ]; then
    Note "Calculating parameters:" "reface"
    # Apply NEW face to native T1w volume
    T1w_mask_brain=${tmp}/mask-brainNeck.nii.gz
    face=${tmp}/face.nii.gz
    refaced=$(bids_add_rec ${out_warps}/${T1w_run1_str}.nii.gz reface)

    Do_cmd antsApplyTransforms -d 3 -u int -i $mics_t1_brainNeck -r $T1_orig -n GenericLabel -t [${T1w_2_mics_mat},1] -o $T1w_mask_brain
    Do_cmd antsApplyTransforms -d 3 -u int -i $mics_t1_face -r $T1_orig -n linear -t [${T1w_2_mics_mat},1] -o $face

    # Reescale the new face
    MaxI=$(fslstats $T1_orig -R | awk '{print $2}')
    Do_cmd ImageMath 3 $face RescaleImage $face 0 $MaxI

    # Apply face to native T1w volume
    Do_cmd fslmaths ${T1w_mask_brain} -mul $T1_orig -add $face $refaced
    if [ ! -f ${refaced} ]; then Error "$refaced refaced failed"; cd $here; Do_cmd exit 0; fi

    # # -----------------------------------------------------------------------------------------------
    # # WARPFACE
    if [ "$METHOD" == "warpface" ] || [ "$METHOD" = "all" ]; then
        Note "Calculating parameters:" "warpface"
        # Binary mask over original T1w_run
        T1w_mask_dil=${tmp}/mask_dil.nii.gz
        T1w_mask_inv=${tmp}/mask_inv.nii.gz

        if [ ! ${dil} -eq 0 ]; then
            # Dilate brain mask
            Do_cmd 3dmask_tool -input $T1w_mask_brain -prefix $T1w_mask_dil -dilate_input $dil
        else
            T1w_mask_dil=$T1w_mask_brain
        fi

        # Inverse the brain mask dilated
        Do_cmd fslmaths $T1w_mask_dil -sub 1 -mul -1 $T1w_mask_inv

        # Create a non-linear warpfield of the face
        T1wrefaced=${tmp}/refaceSyN
        face_warp=${T1wrefaced}_1Warp.nii.gz
        face_mat=${T1wrefaced}_0GenericAffine.mat

        if [[ ${robust} == TRUE ]]; then
            Do_cmd antsRegistrationSyN.sh -d 3 -x $T1w_mask_inv -f $refaced -m $T1_orig -o ${T1wrefaced}_ -t s -n $threads -p f
        else
            Do_cmd antsRegistrationSyNQuick.sh -d 3 -x $T1w_mask_inv -f $refaced -m $T1_orig -o ${T1wrefaced}_ -t s -n $threads -p f
        fi

        # Face-mask the warpfield
        Do_cmd fslmaths $face_warp -mul $T1w_mask_inv $face_warp
        # QC
        if [ ! -f ${face_warp} ]; then Error "$face_warp warpfield calculation failed"; cd $here;  Do_cmd exit 0; fi
    fi
fi

# -----------------------------------------------------------------------------------------------
get_bids_parts() {
    local f="$1"
    local name="${f##*/}"
    name="${name%%.*}"   # strip all extensions

    if [[ "$name" =~ ^(.*)_([^_]+)$ ]]; then
        echo "${BASH_REMATCH[1]}|${BASH_REMATCH[2]}"
    fi
}

get_group_key() {
    local f="$1"
    local prefix suffix

    IFS="|" read -r prefix suffix <<< "$(get_bids_parts "$f")"

    case "$suffix" in
        MP2RAGE|UNIT1|T1map)
            echo "${prefix}_MP2RAGE"
            ;;
        *)
            echo "${prefix}_${suffix}"
            ;;
    esac
}

# --- build group transforms (anchor on inv-1 MP2RAGE) ---
declare -A group_mat

# Loop over all the other structural images (including non T1w volumes)
for nii in "${anat[@]}"; do
  nii=${nii#./}
  nii_pwd="${subject_bids}/anat/${nii}"
  json_file="${nii_pwd%.nii.gz}"
  json_file="${json_file%.nii}.json"

  group=$(get_group_key "$nii")

  if [[ -n "$group" && -n "${group_mat[$group]+_}" ]]; then
      # Group member (e.g. MP2RAGE family) — reuse transform
      Info "REGISTRATION: reusing group mat for $nii"
      Note "De-Identifiying:" "$METHOD"
      Note "Applying to:" "$nii"
      Note "Out string:" "$(bids_add_rec ${nii} $METHOD)"
      nii_out="${tmp}/$(basename "${nii%%.*}")_"
      nii_2_T1_mat="${group_mat[$group]}"
  else
      # Everything else (including T1w, T2w, etc.) — compute its own registration
      Info "REGISTERING | from: $nii | to: $T1w_run1_str"
      Note "De-Identifiying:" "$METHOD"
      Note "Applying to:" "$nii"
      Note "Out string:" "$(bids_add_rec ${nii} $METHOD)"

      nii_out="${tmp}/$(basename "${nii%%.*}")_"
      nii_2_T1_mat="${nii_out}0GenericAffine.mat"

      if [[ "$synth_reg" == "TRUE" ]]; then
          Note "Registration:" "Label based affine registrations"
          nii_synth="${tmp}/nii_synthsegGM.nii.gz"

          Do_cmd mri_synthseg --i "$nii_pwd" --o "${tmp}/nii_synthseg.nii.gz" --threads "$threads" --cpu
          Do_cmd fslmaths "${tmp}/nii_synthseg.nii.gz" -uthr 42 -thr 42 -bin -mul -39 -add "${tmp}/nii_synthseg.nii.gz" "$nii_synth"

          Do_cmd antsRegistrationSyN.sh -d 3 -f $T1_synth -m $nii_synth -o $nii_out -t a -n $threads -p d
      else
          Note "Registration:" "volume based affine registrations"

          Do_cmd antsRegistrationSyN.sh -d 3 -f $T1_orig -m $nii_pwd -o $nii_out -t a -n $threads -p d
      fi
  fi

  # -----------------------------------------------------------------------------------------------
  if [ "$METHOD" == "deface" ] || [ "$METHOD" = "all" ]; then
          roi_deface_anat=${tmp}/${nii/.nii.gz/_}defaceROI.nii.gz
          nii_defaced=${out_warps}/$(bids_add_rec ${nii} deface)
          # Apply face ROI to native T1w volume
          Do_cmd antsApplyTransforms -d 3 -u int -i $roi_deface_T1w -r $nii_pwd -n GenericLabel -t [${nii_2_T1_mat},1] -o $roi_deface_anat
          Do_cmd fslmaths $roi_deface_anat -binv -mul $nii_pwd $nii_defaced
          # Create json
          Do_cmd json_deidentify ${json_file} ${nii_defaced/nii*/json} "deface"
  fi

  # -----------------------------------------------------------------------------------------------
  if [ "$METHOD" == "reface" ] || [ "$METHOD" = "all" ]; then
          nii_refaced=${out_warps}/$(bids_add_rec ${nii} reface)
          nii_face=${tmp}/${nii/.nii.gz/_}face.nii.gz
          nii_mask=${tmp}/${nii/.nii.gz/_}mask-brainNeck.nii.gz

          # Apply NEW face to anat volume
          Do_cmd antsApplyTransforms -d 3 -u int -i $face -r $nii_pwd -n linear -t [${nii_2_T1_mat},1] -o $nii_face
          Do_cmd antsApplyTransforms -d 3 -u int -i $T1w_mask_brain -r $nii_pwd -n linear -t [${nii_2_T1_mat},1] -o $nii_mask

          # Match histogram of the new face and paste it
          MatchI=$(fslstats $nii_pwd -R)
          Do_cmd ImageMath 3 $nii_face RescaleImage $nii_face $MatchI

          # Apply face to native T1w volume
          Do_cmd fslmaths ${nii_mask} -mul $nii_pwd -add $nii_face $nii_refaced
          # Create json
          Do_cmd json_deidentify ${json_file} ${nii_refaced/nii.gz/json} "reface"
  fi

  # -----------------------------------------------------------------------------------------------
  if [ "$METHOD" == "warpface" ] || [ "$METHOD" = "all" ]; then
      nii_warped=${out_warps}/$(bids_add_rec ${nii} warpface)

      # Apply the warpflied
      Do_cmd antsApplyTransforms -d 3 -u int -i $nii_pwd -r $nii_pwd -n NearestNeighbor \
              -t [${nii_2_T1_mat},1] -t [${face_mat},1] -t ${face_warp} -t $face_mat -t ${nii_2_T1_mat} -o $nii_warped
      
      # Create json
      Do_cmd json_deidentify ${json_file} ${nii_warped/nii.gz/json} "warpface"
  fi
done

# -----------------------------------------------------------------------------------------------
# Clean temporal directory
Do_cmd cd $here
if [[ -z $nocleanup ]]; then Do_cmd rm -rf $tmp ${out_warps}/anat; else Info "tmp directory was not erased: ${tmp}"; fi
Note "Temporal directory:  " $tmp
Note "Output directory:    " $out_warps

# -----------------------------------------------------------------------------------------------#
#			 Total Running Time
lopuu=$(date +%s)
eri=$(echo "$lopuu - $aloita" | bc)
eri=$(echo print $eri/60 | perl)
Title "TOTAL running time:\033[38;5;220m $(printf "%0.3f\n" ${eri}) minutes \033[38;5;141m"
bids_variables_unset
