#!/bin/bash
# MICA reface
#
#
# Class: Optional pre processing step (ANONYMIZE)
# we strongly recommend to anonymize the BIDS database before running MICAPIPE
#
#
# Rationale: AFNI's reface algorithm was applied to the T1w native bids anatomical images to obtain
#            a T1w_reface-plus NIFTI.
#            Then a warp filed was calculated from the T1w anatomical image registration (eg. T1w and qT1)
#            to the T1w_reface-plus. The resulting warp fields were then applied to each original
#            anatomical images in order to warp the faces AND maintain the original
#            voxel intensities.
#
# ONLY for scripting and debugging
# TEST=ON
#
# source print funtions for MICAPIPE
source ${MICAPIPE}/functions/utilities.sh

help() {
echo -e "\033[38;5;141m
Usage:    `basename $0`\033[0m  \033[38;5;197m-sub\033[0m <subject_id> \033[38;5;197m-out\033[0m <FULL_PATH/outputDirectory> \033[38;5;197m-bids\033[0m <FULL_PATH/BIDS-directory>\n
\t\t\033[38;5;197m-sub\033[0m 	Subject identification (no 'sub-')
\t\t\033[38;5;197m-out\033[0m 	Output directory for the processed files <anat ORIG and face-warps>.
\t\t\033[38;5;197m-bids\033[0m 	Path to BIDS directory
\t\t\033[38;5;197m-refacePro\033[0m 	Method to anonymize the anat images by creating a new Warped-face
\t\t\033[38;5;197m-reface\033[0m 	Method to anonymize the anat images by creating a new face
\t\t\033[38;5;197m-deface\033[0m 	Method to anonymize the anat images by erasing the face
\t\t\033[38;5;197m-all\033[0m 	        Runs all the previous methods



Warning: This script will replace the ORIGINAL anat volumes for ANONYMIZED in the BIDS directory
         a copy of the original will be save in the OUT directory
         We strongly recomend that the OUT directory is not the BIDS nor the DERIVATIVES

Software versions requirements:
        FSL        19.0.18 or 20.1.12 (https://afni.nimh.nih.gov/download)
        ANTs        2.3.3 (https://github.com/ANTsX/ANTs)
        python 3
          -tensorflow 1.13 or 1.15
          -deep-brain (https://pypi.org/project/deepbrain/)

RRC
McGill University, MNI, MICA-lab, Novemeber 2020
https://github.com/MICA-MNI
http://mica-mni.github.io/
"
}

# -----------------------------------------------------------------------------------------------#
#			ARGUMENTS
# Create VARIABLES
for arg in "$@"
do
  case "$arg" in
  -h|-help)
    help
    exit 1
  ;;
  -sub)
    id=$2
    shift;shift
  ;;
  -out)
    out=$2
    shift;shift
  ;;
  -bids)
    BIDS=$2
    shift;shift
  ;;
  -ses)
    SES=$2
    shift;shift
  ;;
  -reface)
    METHOD="reface"
    shift
  ;;
  -refacePro)
    METHOD="reface-pro"
    shift
  ;;
  -all)
    METHOD="all"
    shift
  ;;
  -deface)
    METHOD="deface"
    shift
  ;;
  -robust)
    robust=TRUE
    shift;shift
  ;;
  -replace)
    replace=TRUE
    shift;shift
  ;;
  -*)
    Error "Unknown option ${2}"
    help
    exit
  ;;
    esac
done

# argument check out & WARNINGS
arg=($id $out $BIDS)
if [ "${#arg[@]}" -lt 3 ]; then
Error "One or more mandatory arguments are missing:"
Note "-sub " $id
Note "-out " "$out"
Note "-bids " "$BIDS"
help; exit 0; fi

# Number of session (Default is "ses-pre")
if [ -z ${METHOD} ]; then Error "The method is missing, add a flag: -deface, -reface -refacePro or -all"; help; exit; fi

# Get the real path of the Inputs
out=`realpath $out`
BIDS=`realpath $BIDS`
id=${id/sub-/}

# Number of session (Default is "ses-pre")
if [ -z ${SES} ]; then export SES="ses-pre"; fi

# CORES should be defined as GLOBAL variable maybe
if [[ -z $CORES ]]; then CORES=6; Info "ANTs will use $CORES CORES"; fi

# Assigns BIDS variables names
bids_variables $BIDS $id $out $SES

# Check BIDS directory
if [ ! -d ${subject_bids} ]; then Error "$id was not found on the BIDS directory\n\t     ${subject_bids}"; exit 0; fi

if [[ ${replace} == TRUE ]]; then
Warning "This script will replace the ORIGINAL anat volumes for ANONYMIZED in the BIDS directory
              a copy of the original anat/volumes will be save in the OUT directory
              We strongly recomend that the OUT directory is not the BIDS nor the DERIVATIVES"
fi

# -----------------------------------------------------------------------------------------------#
#			  Timer & Beginning
aloita=$(date +%s)

# if temporary directory is empty
if [ -z ${tmp} ]; then tmp=/tmp; fi
# Create temporal directory
tmp=${tmp}/${RANDOM}_micapipe_anonymize_${id}
if [ ! -d $tmp ]; then Do_cmd mkdir -p $tmp; fi

# Assign variables
mics_t1=$util_mics/MICs60_T1_0.8mm.nii.gz
mics_t1_ROI=$util_mics/MICs60_T1_0.8mm_mask-defaceROI.nii.gz
mics_t1_face=$util_mics/MICs60_T1_0.8mm_face.nii.gz
mics_t1_brainNeck=$util_mics/MICs60_T1_0.8mm_mask-brainNeck.nii.gz

#------------------------------------------------------------------------------#
Title "Running MICA-anonymize by $METHOD method(s)"

# Check if subject was refaced
DONE=`cat ${BIDS}/CHANGES | grep ${id}-anonymized`
if [[ ! -z $DONE ]]; then Error "Subject $id was already refaced:\n\t\t${DONE}"; exit 0; fi

# Creates OUT directory if it doesn't exist
out_warps=${out}/${id}
Info "Output directory: $out_warps"
if [ ! -d ${out_warps} ]; then Do_cmd mkdir -p ${out_warps}/anat; fi
here=`pwd`

# Get the T1w_run-1 name (no path). Note bids_T1ws come from bids_variables
t1w_run1=`echo ${bids_T1ws[0]} | awk -F 'anat/' '{print $2}'`
for i in ${bids_T1ws[*]}; do echo -e "\t\t$i"; done

# Go to BIDS/anat to create a list of all the Volumes
cd ${subject_bids}/anat
# Create a list with all anat volumes
anat=(`ls *gz`)
# # Remove the T1w_run-1 from anat list
# anat=(${anat[@]/$t1w_run1})
Info "T1w to register: $t1w_run1\n\t\tOther anatomical volumes:"
for i in ${anat[*]}; do echo -e "\t\t$i"; done

# Copy original BIDS to out directory
Do_cmd cp -v *gz ${out_warps}/anat

# move to tmp directory
Do_cmd cd $tmp

T1_orig=${out_warps}/anat/${t1w_run1}
# -----------------------------------------------------------------------------------------------
# Affine registration to MICs60_T1w-atlas
T1w_run1_str=${t1w_run1/.nii.gz/}
T1w_2_MICs=${tmp}/T1w_2_MICs60
T1w_2_mics_mat=${T1w_2_MICs}_0GenericAffine.mat
Do_cmd antsRegistrationSyN.sh -d 3 -f $mics_t1 -m $T1_orig -o ${T1w_2_MICs}_ -t a -n $CORES -p f
if [ ! -f ${T1w_2_mics_mat} ]; then Error "Affine registration failed"; cd $here;  Do_cmd exit 0; fi

# -----------------------------------------------------------------------------------------------
# DEFACE
if [ "$METHOD" == "deface" ] || [ "$METHOD" = "all" ]; then
    Info "DEFACING $t1w_run1"
    roi_deface_t1w=${T1w_2_MICs}_defaceROI.nii.gz
    defaced=${out_warps}/${T1w_run1_str}_defaced.nii.gz

    # Apply face ROI to native T1w volume
    Do_cmd antsApplyTransforms -d 3 -u int -i $mics_t1_ROI -r $T1_orig -n GenericLabel -t [${T1w_2_mics_mat},1] -o $roi_deface_t1w
    Do_cmd fslmaths $roi_deface_t1w -binv -mul $T1_orig $defaced
fi

# -----------------------------------------------------------------------------------------------
# REFACE
if [ "$METHOD" == "reface" ] || [ "$METHOD" = "reface-pro" ] || [ "$METHOD" = "all" ]; then
    Info "REFACING $t1w_run1"
    # Apply NEW face to native T1w volume
    T1w_mask_brain=${tmp}/mask-brainNeck.nii.gz
    face=${tmp}/face.nii.gz
    refaced=${out_warps}/${T1w_run1_str}_refaced.nii.gz

    Do_cmd antsApplyTransforms -d 3 -u int -i $mics_t1_brainNeck -r $T1_orig -n GenericLabel -t [${T1w_2_mics_mat},1] -o $T1w_mask_brain
    Do_cmd antsApplyTransforms -d 3 -u int -i $mics_t1_face -r $T1_orig -n linear -t [${T1w_2_mics_mat},1] -o $face

    # Reescale the new face
    MaxI=`fslstats $T1_orig -R | awk '{print $2}'`
    Do_cmd ImageMath 3 $face RescaleImage $face 0 $MaxI

    # Apply face to native T1w volume
    Do_cmd fslmaths ${T1w_mask_brain} -mul $T1_orig -add $face $refaced
    if [ ! -f ${refaced} ]; then Error "$refaced refaced failed"; cd $here; Do_cmd exit 0; fi

    # # -----------------------------------------------------------------------------------------------
    # # WARPFACE
    if [ "$METHOD" == "reface-pro" ] || [ "$METHOD" = "all" ]; then
        Info "WARP-FACING $t1w_run1"
        # Binary mask over original t1w_run
        T1w_mask_dil=${tmp}/mask_dil.nii.gz
        T1w_mask_inv=${tmp}/mask_inv.nii.gz
        warpfaced=${out_warps}/${T1w_run1_str}_T1w-warpfaced.nii.gz

        # Dilate brain mask
        Do_cmd 3dmask_tool -input $T1w_mask_brain -prefix $T1w_mask_dil -dilate_input 6

        # Inverse the brain mask dilated
        Do_cmd fslmaths $T1w_mask_dil -sub 1 -mul -1 $T1w_mask_inv

        # Create a non-linear warpfield of the face  <<<<<<<<<<< DEFORMABLE Only
        T1wrefaced=${tmp}/refaceSyN
        face_warp=${T1wrefaced}_1Warp.nii.gz
        face_mat=${T1wrefaced}_0GenericAffine.mat

        if [[ ${robust} == TRUE ]]; then
            Do_cmd antsRegistrationSyN.sh -d 3 -x $T1w_mask_inv -f $refaced -m $T1_orig -o ${T1wrefaced}_ -t s -n $CORES -p f
        else
            Do_cmd antsRegistrationSyNQuick.sh -d 3 -x $T1w_mask_inv -f $refaced -m $T1_orig -o ${T1wrefaced}_ -t s -n $CORES -p f
        fi

        # Face-mask the warpfield
        Do_cmd fslmaths $face_warp -mul $T1w_mask_inv $face_warp
        # QC
        if [ ! -f ${face_warp} ]; then Error "$face_warp warpfield calculation failed"; cd $here;  Do_cmd exit 0; fi
        # Apply warpfield to T1w
        # Do_cmd antsApplyTransforms -d 3 -u int -i $T1_orig -r $T1_orig -n linear -t ${face_warp} -o ${warpfaced}
        Do_cmd antsApplyTransforms -d 3 -u int -i $T1_orig -r $T1_orig -n linear -t [${face_mat},1] -t ${face_warp} -t $face_mat -o ${warpfaced}
    fi
fi

# -----------------------------------------------------------------------------------------------
# Loop over all the other structural images (including non T1w volumes)
for nii in ${anat[*]}; do

  # rigid + affine registration 2 steps
  nii_pwd=${out_warps}/anat/${nii}
  nii_out=${tmp}/${nii/.nii.gz/_}
  nii_2_T1_mat=${nii_out}0GenericAffine.mat

  # Do_cmd antsRegistrationSyN.sh -d 3 -f $T1_orig -m anat/${nii} -o ${nii_out} -t a -n $CORES -p d
  Do_cmd antsRegistrationSyN.sh -d 3 -f $T1_orig -m $nii_pwd -o $nii_out -t a -n $CORES -p d

  # -----------------------------------------------------------------------------------------------
  if [ "$METHOD" == "deface" ] || [ "$METHOD" = "all" ]; then
      Info "Applying DEFACING method to $nii"
          roi_deface_anat=${tmp}/${nii/.nii.gz/_}defaceROI.nii.gz
          nii_defaced=${out_warps}/${nii/.nii.gz/_}defaced.nii.gz
          # Apply face ROI to native T1w volume
          Do_cmd antsApplyTransforms -d 3 -u int -i $roi_deface_t1w -r $nii_pwd -n GenericLabel -t [${nii_2_T1_mat},1] -o $roi_deface_anat
          Do_cmd fslmaths $roi_deface_anat -binv -mul $nii_pwd $nii_defaced
  fi

  # -----------------------------------------------------------------------------------------------
  if [ "$METHOD" == "reface" ] || [ "$METHOD" = "all" ]; then
      Info "Applying REFACING method to $nii"
          nii_refaced=${out_warps}/${nii/.nii.gz/_}refaced.nii.gz
          nii_face=${tmp}/${nii/.nii.gz/_}face.nii.gz
          nii_mask=${tmp}/${nii/.nii.gz/_}mask-brainNeck.nii.gz

          # Apply NEW face to anat volume
          Do_cmd antsApplyTransforms -d 3 -u int -i $face -r $nii_pwd -n linear -t [${nii_2_T1_mat},1] -o $nii_face
          Do_cmd antsApplyTransforms -d 3 -u int -i $T1w_mask_brain -r $nii_pwd -n linear -t [${nii_2_T1_mat},1] -o $nii_mask

          # Match histogram of the new face and paste it
          MatchI=`fslstats $nii_pwd -R`
          Do_cmd ImageMath 3 $nii_face RescaleImage $nii_face $MatchI

          # Apply face to native T1w volume
          Do_cmd fslmaths ${nii_mask} -mul $nii_pwd -add $nii_face $nii_refaced
  fi

  # -----------------------------------------------------------------------------------------------
  if [ "$METHOD" == "reface-pro" ] || [ "$METHOD" = "all" ]; then
      Info "Applying Warp-Facing method to $nii"
      nii_warped=${out_warps}/${nii/.nii.gz/_}warpfaced.nii.gz

      # Apply the warpflied
      Do_cmd antsApplyTransforms -d 3 -u int -i $nii_pwd -r $nii_pwd -n linear \
              -t [${nii_2_T1_mat},1] -t ${face_warp} -t ${nii_2_T1_mat} -o $nii_warped
      Do_cmd antsApplyTransforms -d 3 -u int -i $nii_pwd -r $nii_pwd -n linear \
              -t [${nii_2_T1_mat},1] -t [${face_mat},1] -t ${face_warp} -t $face_mat -t ${nii_2_T1_mat} -o $nii_warped

      # rigid + affine + deformable syn (3 stages) <<<<<<<<<<<<<<<<< TRY THIS
      # Do_cmd antsRegistrationSyNQuick.sh -d 3 -f $T1_orig -m anat/${nii} -o ${nii_out} -t s -n $CORES -p d
      # nii_2_T1_warp=${nii_out}1Warp.nii.gz
      # Do_cmd antsApplyTransforms -d 3 -u int -i $nii_pwd -r $T1_orig -n linear \
      #                 -t [${nii_2_T1_mat},1] -t [${nii_2_T1_warp},1] -t ${face_warp} -t ${nii_2_T1_warp} -t ${nii_2_T1_mat} -o $nii_warped

      # # Moving the warpfield to the native anat/nii space
      # warp_in_nii=${tmp}/${nii/.nii.gz/}_warpfield.nii.gz
      # Do_cmd antsApplyTransforms -d 3 -u float -i $face_warp -r $nii_pwd -n linear -t [${nii_2_T1_mat},1] -o $warp_in_nii
      # # Apply face-warp, affine mat, inverse mat and return to native Volume space
      # Do_cmd antsApplyTransforms -d 3 -u int -i $nii_pwd -r $nii_pwd -n linear -t $warp_in_nii -o $nii_warped
  fi
done

#------------------------------------------------------------------------------#
# Replace ORIGINAL BIDS/anat with the ANONYMIZED
if [[ ${replace} == TRUE ]]; then
    for nii in *_warpfaced.nii.gz; do
        Do_cmd cp -v $nii ${subject_bids}/anat/${nii/_warpfaced/}
    done
    echo "${id}-anonymized $(date)" >> ${BIDS}/CHANGES
fi

# -----------------------------------------------------------------------------------------------
# Clean temporal directory
cd $here
# if [[ -z $nocleanup ]]; then Do_cmd rm -rf $tmp; else Info "tmp directory was not erased: ${tmp}"; fi

Note "Temporal directory:  " $tmp
Note "Output directory:    " $out_warps
# -----------------------------------------------------------------------------------------------#
#			 Total Running Time
lopuu=$(date +%s)
eri=$(echo "$lopuu - $aloita" | bc)
eri=`echo print $eri/60 | perl`
Title "TOTAL running time:\033[38;5;220m `printf "%0.3f\n" ${eri}` minutes \033[38;5;141m"
