#!/bin/bash
#
# Test of the variables and PATH for qsub:
#
# Only print a test.
#
# https://github.com/MICA-MNI/micaopen/templates
#
#   ARGUMENTS order:
#   $1 : BIDS directory
#   $2 : participant
#   $3 : Out parcDirectory
#
# ONLY for scripting and debugging:
# TEST=ON
# source utilities
export MICAPIPE=/host/yeatman/local_raid/rcruces/git_here/micapipe
source $MICAPIPE/functions/utilities.sh

BIDS=$1
id=$2
out=$3

here=`pwd`

#------------------------------------------------------------------------------#
Title "Running MICA qsub test"

#	Timer
aloita=$(date +%s)

# Assigns variables names
bids_variables $BIDS $id $out

# if temporary directory is running on MICA-lab SGE
if [ "$PROC" = "qsub-MICA" ];then source ${MICAPIPE}/functions/init.sh; fi
# if temporary directory is empty
if [ -z ${tmp} ]; then tmp=/tmp; fi
# Create temporal directory
tmp=${tmp}/${RANDOM}_micapipe_${subject}
if [ ! -d $tmp ]; then Do_cmd mkdir -p $tmp; fi

# Freesurface SUBJECTs directory
export SUBJECTS_DIR=${dir_surf}

Title ">>> PATHS and Global variables <<<"
Info "Software paths"
Note "User              =" "`whoami`"
Note "Workstation       =" "`uname -n`"
Note "SHELL             =" $SHELL
Note "MICAPIPE          =" $MICAPIPE
Note "AFNIDIR           =" $AFNIDIR
Note "ANTSPATH          =" $ANTSPATH
Note "MRtrix3 bin       =" "`which mrinfo`"
Note "wb_command        =" "`which wb_command`"
Note "FREESURFER_HOME   =" $FREESURFER_HOME
Note "FSLDIR            =" $FSLDIR
Note "FSL_BIN           =" $FSL_BIN
Note "FIXPATH           =" $FIXPATH
Note "FSLPARALLEL       =" $FSLPARALLEL

Info "python: `python --version`"
Note "PYTHONPATH        =" $PYTHONPATH
Note "PYTHONHOME        =" $PYTHONHOME
Note "LC_ALL            =" $LC_ALL
Note "LANG              =" $LANG
Note "LD_LIBRARY_PATH   =" $LD_LIBRARY_PATH

Info "Global variables"
Note "tmp               =" $tmp
Note "CORES             =" $CORES
Note "OMP_NUM_THREADS   =" $OMP_NUM_THREADS
Note "PROC              =" $PROC

# print the names on the terminal
bids_print.variables
bids_print.variables-rsfmri
bids_print.variables-post

# QC notification of completition
lopuu=$(date +%s)
eri=$(echo "$lopuu - $aloita" | bc)
eri=`echo print $eri/60 | perl`

Title "Running MICA qsub test ended in \033[38;5;220m `printf "%0.3f\n" ${eri}` minutes \033[38;5;141m"
echo "${id}, MICAq-TEST, DONE, `whoami`, `uname -n`, $(date), `printf "%0.3f\n" ${eri}`, $PROC" >> ${out}/brain-proc.csv
