#!/bin/bash
#
# MICA pipe Quality Check script
#
# This script will create a basic html file for QC of the processing
#

#
#   ARGUMENTS order:
#   $1 : BIDS directory
#   $2 : participant
#   $3 : Out parcDirectory
#
# ONLY for scripting and debugging:
# TEST=ON
Version="(Version v.0.0.1 'hopelessness')"
version() {
  echo -e "\nMICAPIPE Feb 2021 ${Version}\n"
}
#---------------- FUNCTION: HELP ----------------#
help() {
echo -e "
\033[38;5;141mCOMMAND:\033[0m
$(basename $0)

\033[38;5;141mARGUMENTS:\033[0m
\t\033[38;5;197m-sub\033[0m 	          : Subject identification
\t\033[38;5;197m-out\033[0m 	          : Output directory for the processed files <derivatives>.
\t\033[38;5;197m-bids\033[0m 	          : Path to BIDS directory
\t\033[38;5;120m-ses <str>\033[0m 	  : OPTIONAL flag that indicates the session name (if omitted will manage as SINGLE session)
\t\033[38;5;120m-tracts <int>\033[0m     : OPTIONAL Number of streamlines, where 'M' stands for millions (default=40M)

\033[38;5;141mOPTIONS:\033[0m
\t\033[38;5;197m-h|-help\033[0m          : Print help
\t\033[38;5;197m-tmpDir\033[0m           : Specify location of temporary directory <path> (Default is /tmp)
\t\033[38;5;197m-quiet\033[0m 	          : Do not print comments
\t\033[38;5;197m-nocleanup\033[0m 	  : Do not delete temporal directory at script completion
\t\033[38;5;197m-version\033[0m 	  : Print software version

\033[38;5;141mUSAGE:\033[0m
    \033[38;5;141m$(basename $0)\033[0m \033[38;5;197m-sub\033[0m <subject_id> \033[38;5;197m-out\033[0m <outputDirectory> \033[38;5;197m-bids\033[0m <BIDS-directory>\n

\033[38;5;141mDEPENDENCIES:\033[0m

McGill University, MNI, MICA-lab, May-September 2020
https://github.com/MICA-MNI/micapipe
http://mica-mni.github.io/
"
}

# Check MICAPIPE
if [ -z "${MICAPIPE}" ]; then
echo -e "\033[38;5;1m\n---------------------------------------------------------\n
[ERROR]... MICAPIPE must be define in your enviroment\033[0m
           TRY: export MICAPIPE=<github_Directory>/micasoft\n
\033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 1
fi

if [ ! -f ${MICAPIPE}/functions/utilities.sh ]; then
echo -e "\033[38;5;1m\n---------------------------------------------------------\n
[ERROR]... MICAPIPE is defined, but the PATH is wrong,
           it should match /micasoft directory\033[0m
           CHECK PATH to MICAPIPE:
           $MICAPIPE\n
\033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 1
fi

# Source utilities functions from MICAPIPE
source ${MICAPIPE}/functions/utilities.sh

# -----------------------------------------------------------------------------------------------#
#			ARGUMENTS
# Create VARIABLES
for arg in "$@"
do
  case "$arg" in
  -h|-help)
    help
    exit 1
  ;;
  -version)
    version
    exit 1
  ;;
  -sub)
    id=$2
    shift;shift
  ;;
  -out)
    out=$2
    shift;shift
  ;;
  -bids)
    BIDS=$2
    shift;shift
  ;;
  -ses)
    SES=$2
    shift;shift
  ;;
  -tracts)
    tracts=$2
    shift;shift
  ;;
  -mica)
    mica=TRUE
    shift
  ;;
  -nocleanup)
    nocleanup=TRUE
    shift
  ;;
  -tmpDir)
    tmpDir=$2
    shift;shift;
  ;;
  -*)
    Error "Unknown option ${2}"
    help
    exit 1
  ;;
    esac
done

# argument check out & WARNINGS
arg=($id $out $BIDS)
if [ "${#arg[@]}" -lt 3 ]; then
Error "One or more mandatory arguments are missing:
               -sub  : $id
               -out  : $out
               -bids : $BIDS"
help; exit 1; fi

# Get the real path of the Inputs
out=$(realpath $out)/micapipe
BIDS=$(realpath $BIDS)
id=${id/sub-/}
here=$(pwd)

# Number of session (Default is "ses-pre")
if [ -z ${SES} ]; then SES="SINGLE"; else SES="ses-${SES/ses-/}"; fi

# Exit if subject is not found
if [ ! -d ${out}/sub-${id} ]; then Error "$id was not found on the OUTPUT directory\n\t Check ls ${out}/sub-${id}/${SES}"; exit 1; fi

# Optional arguments number of tracts
if [ -z ${tracts} ]; then tracts=40M; else tracts=$tracts; fi

# Temporal directory
if [ -z ${tmpDir} ]; then export tmpDir=/tmp/${RANDOM}_micapipe_QC_${id}; else tmpDir=$(realpath $tmpDir); fi

# Erase temporal files by default
if [ -z ${nocleanup} ]; then nocleanup=FALSE; fi

# Processing
if [[ -z $PROC ]]; then export PROC="LOCAL"; fi
if [ "$mica" = "TRUE" ]; then
    # Launch the init file.
    source ${MICAPIPE}/functions/init.sh
    if [[ $? != 0 ]]; then
      Error "Could not find init file. Is this script in the\n base directory of the MICAPIPE github and in init \nfile in the functions subdirectory?"; exit 1
    fi
fi

# Assigns variables names
bids_variables $BIDS $id $out $SES

procDirs=$(ls -d ${subject_dir}/anat ${subject_dir}/dwi ${subject_dir}/func | wc -l)
if [ "${procDirs}" -lt 3 ]; then
Error "Wrong path to subject_dir, Did you forget the -ses (SINGLE by default)?:
               -ses  : $SES"
help; exit 1; fi

# Variables
parcellations=$(find ${dir_volum} -name "*.nii.gz" ! -name "*cerebellum*" ! -name "*subcortical*" | sort)
workflow=${dir_QC}/micapipe_workflow.html

#------------------------------------------------------------------------------#
Title "MICAPIPE: Creating a QC html file for $id"
micapipe_software
micapipe_json
bids_print.variables
bids_print.variables-post
bids_print.variables-dwi
bids_print.variables-rsfmri

#------------------------------------------------------------------------------#
# Create files and png for QC
# Create tmp dir
if [ ! -d ${tmpDir} ]; then Do_cmd mkdir -p $tmpDir; fi

# TRAP in case the script fails
trap 'cleanup $tmp $nocleanup $here' SIGINT SIGTERM

# Calculate everythin on a tmpDir dir
cd $tmpDir

# Mean Noise residuals
# mrmath 37149_dwi_residuals.mif mean 37149_dwi_residuals_mean.mif -axis 3

# Required Info for eddy_quad
# mrinfo 37149_dwi_corr.mif -force -json_all 37149_dwi_corr.json -dwgrad > grad.txt
# mrinfo HC10_dwi_corr.mif -dwgrad > HC10_dwi_corr-grad.txt

# Do autotract only if dir exists
if [ -d "$autoTract_dir" ]; then
  Ntracts=0 # 14 tracts tested for QC
  COMMAND_tract=""
  for tck in CG_L CG_R CST_L CST_R ILF_L ILF_R SLF_L SLF_R AF_L AF_R UF_L UF_R FMA FMI; do
      tck_nom=$autoTract_dir/${id}_${tracts}_${tck}.tck
      if [[ -f $tck_nom ]]; then
        ((Ntracts++));
        COMMAND_tract=$(echo -e "${COMMAND_tract} -tractography.load $tck_nom -tractography.opacity 0.15 -tractography.thickness 0 -tractography.geometry lines -tractography.slab -1")
      fi
  done
  # Create png
  Info "Autotract QC found $Ntracts out of 14 tested bundles, creating png"
  for plane in 0 1; do
     COMMAND="mrview $autoTract_dir/${id}_${tracts}_atlas2fa.nii.gz -mode 1 -plane $plane -colourbar 0 -comments 0 -voxelinfo 0 -focus 0 -intensity_range 0,100000 -imagevisible 1 $COMMAND_tract -capture.grab -exit"
     $COMMAND
     mv -v screenshot*.png ${dir_QC_png}/QC_autotract_plane${plane}.png
  done
fi

cd $here

#------------------------------------------------------------------------------#
# Individual QC html file
QC_html=${dir_QC}/${id}_micapipe_qc.html
px=200px
table_style=" <style type=\"text/css\">
  .tg  {border-collapse:collapse;border-spacing:0;}
  .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
    overflow:hidden;padding:10px 5px;word-break:normal;}
  .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
    font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
  .tg .tg-rkbl{background-color:#ecf4ff;border-color:#ffffff;color:#000000;
    font-family:\"Trebuchet MS\", Helvetica, sans-serif !important;;text-align:center;vertical-align:middle}
  .tg .tg-wk8r{background-color:#ffffff;border-color:#ffffff;text-align:center;vertical-align:center}
  .tg .tg-droi{background-color:#ecf4ff;border-color:#ffffff;color:#656565;
    font-family:\"Trebuchet MS\", Helvetica, sans-serif !important;;text-align:center;vertical-align:middle}
  .tg .tg-8hoh{background-color:#c0c0c0;border-color:inherit;font-family:\"Courier New\", Courier, monospace !important;;font-size:16px;
    text-align:center;vertical-align:top}
  .tg .tg-dp6t{border-color:inherit;font-family:\"Courier New\", Courier, monospace !important;;font-size:16px;text-align:center;
    vertical-align:top}
  .tg .tg-8pnm{background-color:#ffffff;border-color:#ffffff;color:#333333;font-family:\"Courier New\", Courier, monospace !important;;
    font-size:16px;text-align:left;vertical-align:top}
  </style>"

#	Timer
aloita=$(date +%s)

echo "<!doctype html>
<html>
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title> MICAPIPE QC - Subject: ${id} - Session: ${SES}</title>

  <!-- Java accordion script -->
  <link rel=\"stylesheet\" type=\"text/css\" href=\"http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css\" />
              <script type=\"text/javascript\" language=\"javascript\" src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>
              <script type=\"text/javascript\" language=\"javascript\" src=\"http://code.jquery.com/ui/1.10.3/jquery-ui.js\"></script>
              <script type=\"text/javascript\" language=\"javascript\">
                  \$(function() {
                      \$( \"#accordion\" ).accordion({
                          collapsible: true,
                          heightStyle: \"content\",
                          animate: {
                              duration: 200,
                              down: {
                                  easing: \"easeOutBounce\",
                                  duration: 1000
                              }
                          }
                      });
                  });
              </script>

  <!-- Accordion script -->
  <style>
  .accordion {
    background-color: #eee;
    color: #656565;
    font-family:\"Trebuchet MS\", Helvetica, sans-serif !important;;
    cursor: pointer;
    padding: 15px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 18px;
    transition: 0.4s;
  }

  .active, .accordion:hover {
    background-color: #ccc;
  }

  .accordion:after {
    content: '\\002B';
    color: #777;
    font-weight: bold;
    float: right;
    margin-left: 5px;
  }

  .active:after {
    content: \"\\2212\";
  }

  .panel {
    padding: 0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
  }
  </style>

  <!-- Headings format -->
  <style>
    h1 {color:#343434;font-family:\"Trebuchet MS\", Helvetica, sans-serif !important;;text-align:center;}
    h2 {color:#656565;font-family:\"Trebuchet MS\", Helvetica, sans-serif !important;;}
    h3 {color:#343434;font-family:\"Trebuchet MS\", Helvetica, sans-serif !important;;}
    p {color:#656565;font-family:\"Trebuchet MS\", Helvetica, sans-serif !important;;}
    a {color:#343434;font-family:\"Trebuchet MS\";}
  </style>

  <!-- Navigation Bar script -->
  <style>
  body {
    font-family: \"Lato\", sans-serif;
  }
  .sidenav {
    height: 100%;
    width: 200px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    padding-top: 40px;
  }

  .sidenav a {
    padding: 6px 6px 6px 32px;
    text-decoration: none;
    font-size: 16px;
    color: #818181;
    display: block;
  }

  .sidenav a:hover {
    color: #f1f1f1;
  }

  .main {
    margin-left: 200px; /* Same as the width of the sidenav */
  }

  @media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
  }
  </style>

  <!-- Sticky image -->
  <style>
  img.sticky {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    width: 200px;
  }
  </style>

</head>
<body>" >  $QC_html

#------------------------------------------------------------------------------#
# Navigation bar
echo -e "
<div class=\"sidenav\">
    <a href=\"#top\"><img src=\"${MICAPIPE}/docs/figures/micapipe_small_black.png\" style=\"width:100%\"  alt=\"micapipe\"></a>
    <a href=\"#top\" style=\"color:white; font-size: 17px\">QC: ${id}_${SES}</a>
    <a href=\"#workflow\">Workflow</a>
    <a href=\"#procStruct\">proc_structural</a>
    <a href=\"#freesurfer\">proc_freesurfer</a>
    <a href=\"#postStruct\">post_structural</a>
    <a href=\"#diffusion\">proc_dwi</a>
    <a href=\"#resting\">proc_rsfmri</a>
    <a style=\"margin-left: 1rem; font-size: 14px\" href=\"#functionalConn\">Functional connectomes</a>
    <a href=\"#structuralConn\">Structural Connectomes</a>
    <a href=\"#mpc\">Microstructural profile covariance (MPC)</a>
    <a href=\"#gd\">Geodesic distance (GD)</a>
    <a href=\"#mpcGD\">MPC & GD connectomes</a>
    <a href=\"#morphology\">Cortical morphology</a>">> $QC_html
if [ -d "$autoTract_dir" ]; then
echo -e "    <a href=\"#autoTract\">Automatic bundle segmentation</a>" >> $QC_html
fi
echo -e "    <a href=\"#info\">Info</a>
</div>" >> $QC_html

#------------------------------------------------------------------------------#
# MICAPIPE processing flowchart
echo -e "
<img id=\"top\" src=\"${MICAPIPE}/docs/figures/micapipe_long.png\" style=\"width:100%\"  alt=\"micapipe\">
<h1>Subject: ${id}, session: ${SES}</h1>
<div class=\"main\">
      <div id=\"accordion\">
          <h3 id=\"workflow\">Workflow</h3>
          <div>
              <iframe width=\"600\" src=\"$workflow\" title=\"Processed modules\" style=\"border: none; overflow: hidden; height: 70%;
                width: 80%; position: absolute;\"></iframe>
              <br>\n<br>\n<br>\n<br>\n<br>\n<br>\n<br><br>\n<br>\n<br>\n<br>\n<br>\n<br>\n<br>\n<br>\n<br>\n<br>\n<br><br>\n<br>\n<br>\n<br>\n<br>\n<br>
              <p>Modules already processed are shown as colored nodes.</p>
          </div>
      </div>"  >> $QC_html



#------------------------------------------------------------------------------#
# MICAPIPE Processing Modules QC
# QC rsfMRI
# /data_/mica3/BIDS_MIC/derivatives/sub-HC011/ses-01/proc_rsfmri/surfaces
# Include html into html: https://stackoverflow.com/questions/8988855/include-another-html-file-in-a-html-file
echo -e "\n    <button class=\"accordion\" id=\"procStruct\">Structural processing: -proc_anat</button>
    <div class=\"panel\">
    <h3>Input files</h3>" >> $QC_html
    echo -e $table_style >> $QC_html
    echo -e "
        <table class=\"tg\">
          <thead>
            <tr>
              <th class=\"tg-rkbl\">Variable name</th>
              <th class=\"tg-droi\">Origin</th>
              <th class=\"tg-droi\">Path to file</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">t1ref</span></td>
              <td class=\"tg-8pnm\">BIDS anat<br><br></td>
              <td class=\"tg-8pnm\">${bids_T1ws[0]}</td>
            </tr>
            " >> $QC_html
N=${#bids_T1ws[@]}
n=$((${N} - 1))
if [ "$N" -gt 1 ]; then
  for ((i=1; i<=$n; i++)); do
    echo "
            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1run_$((${i}+1))</span></td>
              <td class=\"tg-8pnm\">BIDS anat<br><br></td>
              <td class=\"tg-8pnm\">${bids_T1ws[$i]}</td>
            </tr>" >> $QC_html
  done
fi
    echo -e "
          </tbody>
          </table>
  </div>"  >> $QC_html

#------------------------------------------------------------------------------#
echo "
    <button class=\"accordion\" id=\"freesurfer\">Freesurfer processing: -proc_freesurer</button>
    <div class=\"panel\">
    <h3>Input files</h3>" >> $QC_html
    echo -e $table_style >> $QC_html
    echo -e "
        <table class=\"tg\">
          <thead>
            <tr>
              <th class=\"tg-rkbl\">Variable name</th>
              <th class=\"tg-droi\">Origin</th>
              <th class=\"tg-droi\">Path to file</th>
            </tr>
          </thead>
          <tbody>" >> $QC_html
N=${#bids_T1ws[@]}
n=$((${N} - 1))
if [ "$N" -gt 1 ]; then
  for ((i=0; i<=$n; i++)); do
    echo "
            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">bids_T1ws[${i}]</span></td>
              <td class=\"tg-8pnm\">BIDS anat<br><br></td>
              <td class=\"tg-8pnm\">${bids_T1ws[$i]}</td>
            </tr>" >> $QC_html
  done
fi
    echo -e "
          </tbody>
          </table>
    </div>"  >> $QC_html
# $QA_TOOLS/recon_checker -help
# https://surfer.nmr.mgh.harvard.edu/fswiki/QATools

#------------------------------------------------------------------------------#
# POST-STRUCTRURAL QC
mat_MNI152_SyN=${dir_warp}/${T1str_nat}_brain_to_0.8mm_MNI152_SyN_brain_    # transformation strings nativepro to MNI152_0.8mm
T1_MNI152_InvWarp=${mat_MNI152_SyN}1InverseWarp.nii.gz                      # Inversewarp - nativepro to MNI152_0.8mm
T1_MNI152_affine=${mat_MNI152_SyN}0GenericAffine.mat

echo "
    <button class=\"accordion\" id=\"postStruct\">Post-structural processing: -post_structural</button>
    <div class=\"panel\">
      <h3>Input files</h3>" >> $QC_html
  echo -e $table_style >> $QC_html
  echo -e "      <table class=\"tg\">
        <thead>
          <tr>
            <th class=\"tg-rkbl\">Variable name</th>
            <th class=\"tg-droi\">Origin</th>
            <th class=\"tg-droi\">Path to file</th>
          </tr>
          <tr>
            <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1freesurfr</span></td>
            <td class=\"tg-8pnm\">proc_freesurfer<br><br></td>
            <td class=\"tg-8pnm\">${T1freesurfr}</td>
          </tr>
          <tr>
            <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1nativepro</span></td>
            <td class=\"tg-8pnm\">proc_structural<br><br></td>
            <td class=\"tg-8pnm\">${proc_struct}/${id}_t1w_${res}mm_nativepro.nii.gz</td>
          </tr>
            <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1fast_seg</span></td>
            <td class=\"tg-8pnm\">proc_structural<br><br></td>
            <td class=\"tg-8pnm\">$(find $T1fast_seg 2>/dev/null)</td>
          </tr>
          <tr>
            <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1_MNI152_InvWarp</span></td>
            <td class=\"tg-8pnm\">proc_structural<br><br></td>
            <td class=\"tg-8pnm\">$(find $T1_MNI152_InvWarp 2>/dev/null)</td>
          </tr>
          <tr>
            <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1_MNI152_affine</span></td>
            <td class=\"tg-8pnm\">proc_structural<br><br></td>
            <td class=\"tg-8pnm\">$(find $T1_MNI152_affine 2>/dev/null)</td>
          </tr>" >> $QC_html
          echo -e "
                </tbody>
                </table>"  >> $QC_html
#------------------------------------------------------------------------------#
echo -e "<h3>Output volumetric parcellations</h3>" >> $QC_html
echo -e $table_style >> $QC_html
echo -e "      <table class=\"tg\">
      <thead>
        <tr>
          <th class=\"tg-rkbl\">Parcellation</th>
          <th class=\"tg-droi\">Path to file</th>
        </tr>" >> $QC_html
# Prepare the segmentatons
parcellations=`find ${dir_volum} -name "*.nii.gz" ! -name "*cerebellum*" ! -name "*subcortical*"`
for seg in $parcellations; do
    parc_name=`echo ${seg/.nii.gz/} | awk -F 'nativepro_' '{print $2}'`
    echo -e "
              <tr>
                <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">${parc_name}</span></td>
                <td class=\"tg-8pnm\">${seg}</td>
              </tr>"  >> $QC_html
done
echo -e "
      </tbody>
      </table>
    </div>" >> $QC_html

#------------------------------------------------------------------------------#
echo "
    <button class=\"accordion\" id=\"diffusion\">Diffusion MRI processing: -proc_dwi</button>
    <div class=\"panel\">
      <h3>Input files</h3>" >> $QC_html
    echo -e $table_style >> $QC_html
    echo -e "
        <table class=\"tg\">
          <thead>
            <tr>
              <th class=\"tg-rkbl\">Variable name</th>
              <th class=\"tg-droi\">Origin</th>
              <th class=\"tg-droi\">Path to file</th>
            </tr>
          </thead>
          <tbody>" >> $QC_html

# proc_dwi inputs Main DWI(s) and Reverse Phase Encoding
  if [ ! -f ${dir_QC}/micapipe_qc_proc-dwi.txt ]; then QC_proc-dwi; fi
  cat ${dir_QC}/micapipe_qc_proc-dwi.txt >> $QC_html

# Other inputs
    echo -e "            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1nativepro</span></td>
              <td class=\"tg-8pnm\">proc_structural<br><br></td>
              <td class=\"tg-8pnm\">$(find $T1nativepro 2>/dev/null)</td>
            </tr>
            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1_MNI152_InvWarp</span></td>
              <td class=\"tg-8pnm\">proc_structural<br><br></td>
              <td class=\"tg-8pnm\">$(find $T1_MNI152_InvWarp 2>/dev/null)</td>
            </tr>
            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1_MNI152_affine</span></td>
              <td class=\"tg-8pnm\">proc_structural<br><br></td>
              <td class=\"tg-8pnm\">$(find $T1_MNI152_affine 2>/dev/null)</td>
            </tr>
            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T15ttgen</span></td>
              <td class=\"tg-8pnm\">proc_structural<br><br></td>
              <td class=\"tg-8pnm\">$(find $T15ttgen 2>/dev/null)</td>
            </tr>
          </tbody>
          </table>"  >> $QC_html
echo -e "\n        <h3>Motion parameters</h3>" >> $QC_html
echo -e "\n        <h3>Noise estimation</h3>" >> $QC_html
echo -e "\n    </div>" >> $QC_html

#------------------------------------------------------------------------------#
# RESTING STATE
echo -e "
    <button class=\"accordion\" id=\"resting\">Resting state fMRI processing: -proc_rsfmri</button>
    <div class=\"panel\">
      <h3>Input files</h3>" >> $QC_html
    echo -e $table_style >> $QC_html
    echo -e "
        <table class=\"tg\">
          <thead>
            <tr>
              <th class=\"tg-rkbl\">Variable name</th>
              <th class=\"tg-droi\">Origin</th>
              <th class=\"tg-droi\">Path to file</th>
            </tr>
          </thead>
          <tbody>"  >> $QC_html
# proc_rsfmri Input files
if [ ! -f ${dir_QC}/micapipe_qc_proc-rsfmir.txt ]; then QC_proc-rsfmri; fi
cat ${dir_QC}/micapipe_qc_proc-rsfmir.txt >> $QC_html

echo -e "
            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1nativepro</span></td>
              <td class=\"tg-8pnm\">proc_structural<br><br></td>
              <td class=\"tg-8pnm\">$(find $T1nativepro 2>/dev/null)</td>
            </tr>
            <tr>
              <td class=\"tg-8pnm\"><span style=\"font-weight:bold\">T1freesurfr</span></td>
              <td class=\"tg-8pnm\">proc_freesurfer<br><br></td>
              <td class=\"tg-8pnm\">$(find $T1freesurfr 2>/dev/null)</td>
            </tr>
          </tbody>
          </table>"  >> $QC_html
# rsfmri motion parameters
echo -e "\n      <h3>Motion parameters: rsfMRI</h3>" >> $QC_html
# Fuctional Connectomes
echo -e "\n      <h3 id=\"functionalConn\">Functional connectomes</h3>" >> $QC_html
echo -e $table_style >> $QC_html
echo -e "
    <table class=\"tg\">
      <thead>
        <tr>
          <th class=\"tg-rkbl\">Parcellation<br>scheme</th>
          <th class=\"tg-droi\">Functional <br>connectome</th>
          <th class=\"tg-droi\">FC conte69</th>
        </tr>
      </thead>
      <tbody>" >> $QC_html

# iterate over each FC png file
Nconn=$(ls ${dir_QC_png}/*_FC*.png 2>/dev/null | wc -l)
if [ ! "$Nconn" -eq 0 ]; then
  for seg in $parcellations; do
      parc_name=$(echo ${seg/.nii.gz/} | awk -F 'nativepro_' '{print $2}')
      echo -e " <tr>
            <td class=\"tg-droi\">${parc_name}</td>"  >> $QC_html
      for ext in FC FC-conte69; do
          nom=${dir_QC_png}/${id}_${parc_name}_${ext}.png
          if [ -f "$nom" ]; then
              echo "            <td class=\"tg-wk8r\"><img src=\"${nom}\"  alt=\"HTML5\" style=\"width:${px};height:${px}\"></td>" >> $QC_html
          else
              echo "            <td class=\"tg-8hoh\"><br><br><span style=\"font-weight:bold\">File Not Found:</span><br><br><span style=\"font-weight:bold\">\"${id}_${parc_name}_${ext}.png\"</span><br><br></td>"  >> $QC_html
          fi
      done
      echo "  </tr>" >> $QC_html
  done
else
  echo "  <p> ...Not processed yet... </p>" >>  $QC_html
fi
# Close functional connectome QC table
echo -e "
    </tbody>
    </table>
   </div>
 "  >> $QC_html

 #------------------------------------------------------------------------------#
 # Diffusion processing MRI
 echo -e "
     <button class=\"accordion\" id=\"structuralConn\">Structural Connectomes: -SC</button>
     <div class=\"panel\">
       <h3>Input files</h3>" >> $QC_html
 #-------------------------------------
 # SC - Inputs files
 if [ -f $tdi ]; then
   # Input files table
   echo -e $table_style >> $QC_html
   echo -e "
       <table class=\"tg\">
         <thead>
           <tr>
             <th class=\"tg-rkbl\">Variable name</th>
             <th class=\"tg-droi\">Origin</th>
             <th class=\"tg-droi\">Path to file</th>
           </tr>
         </thead>
         <tbody>"  >> $QC_html

   # Structural connectomes Input files
   # if [ ! -f ${dir_QC}/micapipe_qc_SC.txt ]; then QC_SC; fi
   cat ${dir_QC}/micapipe_qc_SC.txt >> $QC_html

   echo -e "
         </tbody>
         </table>"  >> $QC_html
   #-------------------------------------
   # Here goes a TDI png image
 else
   echo "  <p> ...Not processed yet... </p>" >> $QC_html
 fi

 #-------------------------------------
 # SC - Output connectomes
 echo -e "<h3>Structural Connectomes</h3>" >> $QC_html
 echo -e $table_style >> $QC_html
 echo -e "
       <table class=\"tg\">
       <thead>
         <tr>
           <th class=\"tg-rkbl\">Parcellation<br>scheme</th>
           <th class=\"tg-droi\">Cortical <br>connectome</th>
           <th class=\"tg-droi\">Cortical-Subcortical <br>Connectome</th>
           <th class=\"tg-droi\">Full <br>Connectome</th>
           <th class=\"tg-droi\">Cortical <br>Edge lengths</th>
           <th class=\"tg-droi\"><span style=\"font-style:normal\">Cortical-Subcortical </span><br><span style=\"font-style:normal\">Edge lengths</span></th>
           <th class=\"tg-droi\"><span style=\"font-style:normal\">Full </span><br><span style=\"font-style:normal\">Edge lengths</span></th>
         </tr>
       </thead>
       <tbody>" >> $QC_html

 # Iterate over all the parcellation
 Nconn=$(ls ${dir_QC_png}/*connectome.png 2>/dev/null | wc -l)
 if [ ! "$Nconn" -eq 0 ]; then
   for seg in $parcellations; do
       parc_name=`echo ${seg/.nii.gz/} | awk -F 'nativepro_' '{print $2}'`
       echo -e " <tr>
             <td class=\"tg-droi\">${parc_name}</td>"  >> $QC_html
       for ext in cor-connectome sub-connectome full-connectome cor-edgeLengths sub-edgeLengths full-edgeLengths; do
           nom=${dir_QC_png}/${id}_${tracts}_${parc_name}_${ext}.png
           if [ -f "$nom" ]; then
               echo "            <td class=\"tg-wk8r\"><img src=\"${nom}\"  alt=\"HTML5\" style=\"width:${px};height:${px}\"></td>" >> $QC_html
           else
               echo "            <td class=\"tg-8hoh\"><br><br><span style=\"font-weight:bold\">File Not Found:</span><br><br><span style=\"font-weight:bold\">\"${id}_${tracts}_${parc_name}_${ext}.png\"</span><br><br></td>"  >> $QC_html
           fi
       done
       echo "  </tr>" >> $QC_html
   done
 else
   echo "  <p> ...Not processed yet... </p>" >> $QC_html
 fi

 # Close Structural connectome QC table
 echo -e "
       </tbody>
       </table>
   </div>
 "  >> $QC_html

#------------------------------------------------------------------------------#
echo "
    <button class=\"accordion\" id=\"mpc\">Microstructural profile covariance: -MPC</button>
    <div class=\"panel\">
      <h3>Input files</h3>" >> $QC_html
echo "
    </div>"  >> $QC_html

#------------------------------------------------------------------------------#
echo "
    <button class=\"accordion\" id=\"gd\">Geodesic distance: -GD</button>
    <div class=\"panel\">
          <h3>Input files</h3>" >> $QC_html
echo "
    </div>"  >> $QC_html

#-------------------------------------
echo "
    <button class=\"accordion\" id=\"mpcGD\">MPC and GD Connectomes</button>
    <div class=\"panel\">" >> $QC_html
echo -e $table_style >> $QC_html
echo -e "
        <table class=\"tg\">
          <thead>
            <tr>
              <th class=\"tg-rkbl\">Parcellation<br>scheme</th>
              <th class=\"tg-droi\">MPC Connectome</th>
              <th class=\"tg-droi\">MPC Intensity</th>
              <th class=\"tg-droi\">Geodesic <br>Distance</th>
            </tr>
          </thead>
          <tbody>" >> $QC_html

# Iterate over all the parcellation
for seg in $parcellations; do
    parc_name=`echo ${seg/.nii.gz/} | awk -F 'nativepro_' '{print $2}'`
    echo -e " <tr>
          <td class=\"tg-droi\">${parc_name}</td>"  >> $QC_html
    for ext in MPC MPC-intensity GD; do
        Nfiles=$(ls ${dir_QC_png}/*_${ext}.png 2>/dev/null | wc -l)
        # echo "Nfiles=$Nfiles Modality=$ext"
        if [ "$Nfiles" -eq 0 ]; then
            Message="\"tg-dp6t\"><br><br><span style=\"font-weight:bold\">>>>   Module not   <<<</span><br><span style=\"font-weight:bold\">processed:</span><br><span style=\"font-weight:bold\">-${ext/-intensity/}";
        else
            Message="\"tg-8hoh\"><br><br><span style=\"font-weight:bold\">File Not Found:</span><br><br><span style=\"font-weight:bold\">\"${id}_${parc_name}_${ext}.png\"";
        fi
        nom=${dir_QC_png}/${id}_${parc_name}_${ext}.png
        if [ -f "$nom" ]; then
            echo "            <td class=\"tg-wk8r\"><img src=\"${nom}\"  alt=\"HTML5\" style=\"height:${px}\"></td>" >> $QC_html
        else
            echo "            <td class=${Message}</span><br><br></td>"  >> $QC_html
        fi
    done
    echo "  </tr>" >> $QC_html
done

# Close MPC and GD QC table
echo -e "
        </tbody>
        </table>
    </div>"  >> $QC_html

#------------------------------------------------------------------------------#
echo -e "\n  <button class=\"accordion\" id=\"morphology\">Cortical morphology</button>
  <div class=\"panel\">
    <h3>Input files</h3>
    <p>... work in progress ...</p>
  </div>" >> $QC_html

#------------------------------------------------------------------------------#
# Do autotract only if dir exists
if [ -d "$autoTract_dir" ]; then
  echo "
    <button class=\"accordion\" id=\"autoTract\">Automatic bundle segmentation</button>
    <div class=\"panel\">" >> $QC_html
echo -e "\n      <h3>Input files</h3>" >> $QC_html
echo -e "\n      <h3>Outputs files</h3>" >> $QC_html
echo -e "\n      <h3>Sagital view: QC segmentations of $Ntracts tracts</h3>
        <img src=\"${dir_QC_png}/QC_autotract_plane0.png\" width=\"625\" height=\"530\">
      <h3>Coronal view: QC segmentations of $Ntracts tracts</h3>
        <img src=\"${dir_QC_png}/QC_autotract_plane1.png\"  width=\"625\" height=\"530\">
    </div>" >> $QC_html
fi

#------------------------------------------------------------------------------#
# Do autotract only if dir exists
if [ -d "$autoTract_dir" ]; then
  echo "
    <button class=\"accordion\" id=\"info\">Info</button>
    <div class=\"panel\">" >> $QC_html
echo -e "
      <p>
      <b>micapipe version:</b> $Version<br>
      <b>User:</b>$(whoami)<br>
      <b>Workstation:</b>$(uname -n)<br>
      <b>Last run:</b>$(date)
      </p>
    </div>" >> $QC_html
fi

#------------------------------------------------------------------------------#
# Accordion config
echo -e "
<script>
var acc = document.getElementsByClassName(\"accordion\");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener(\"click\", function() {
    this.classList.toggle(\"active\");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + \"px\";
    }
  });
}
</script>"  >> $QC_html

#------------------------------------------------------------------------------#
# closes html document
echo "
</div>

</body>
</html>" >> $QC_html

# -----------------------------------------------------------------------------------------------
# QC notification of completition
lopuu=$(date +%s)
eri=$(echo "$lopuu - $aloita" | bc)
eri=$(echo print $eri/60 | perl)

# Cleanup if processing was local
if [ -d $tmpDir ]; then
    cleanup $tmpDir $nocleanup $here
fi

Title "QC html creation ended in \033[38;5;220m $(printf "%0.3f\n" ${eri}) minutes \033[38;5;141m:
\t\tOutput file path: $QC_html"
