#!/bin/bash
# MICA change Space
#
#
# Class: support function
#
#
# Rationale: This function takes a VOLUME as input and apply the necessary transformations
#            to change the VOLUME SPACE, eg.:
#               > nativepro to freesurfer and inverse
#               > native to native pro
#               > nativepro to dwi
#            etc...
# source print funtions for MICAPIPE
source ${MICAPIPE}/functions/utilities.sh

#---------------- FUNCTION: HELP ----------------#
help() {
echo -e "\033[38;5;141m
Usage:    `basename $0`\033[0m  \033[38;5;197m-sub\033[0m <subject_id> \033[38;5;197m-derivatives\033[0m <PATH-TO/derivativesDirectory> \033[38;5;197m-in\033[0m <input volume> \033[38;5;197m-space\033[0m <NEW space>\n


This function takes a VOLUME as input and apply the necessary transformations to change the VOLUME SPACE.
\t\t\033[38;5;197m-sub\033[0m 	Subject identification (no 'sub-')
\t\t\033[38;5;197m-out\033[0m 	Derivatives directory for the processed files <derivatives>.
\t\t\033[38;5;197m-in\033[0m 	Input volume to register to a new space
\t\t\033[38;5;197m-space\033[0m 	New space (native, nativepro, freesurfer, dwi)

Check our documentation for further information about spaces:
    .....not ready yet.....

McGill University, MNI, MICA-lab, May 2020
Written by RRC
https://github.com/MICA-MNI
http://mica-mni.github.io/
"
}

# -----------------------------------------------------------------------------------------------#
#			ARGUMENTS
# Create VARIABLES
for arg in "$@"
do
  case "$arg" in
  -h|-help)
    help
    exit 1
  ;;
  -sub)
    id=$2
    shift;shift
  ;;
  -derivatives)
    derv=$2
    shift;shift
  ;;
  -in)
    in=$2
    shift
  ;;
  -space)
    space=$2
    shift;shift
  ;;
  -*)
   Error "Unknown option ${2}"
   help
   exit
  ;;
   esac
done
