# Generated by: Neurodocker version 0.7.0+0.gdc97516.dirty
# Latest release: Neurodocker version 0.9.5
# Timestamp: 2023/05/18 01:58:52 UTC
#
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
#
#     https://github.com/ReproNim/neurodocker

FROM ubuntu:bionic-20201119

USER root

ARG DEBIAN_FRONTEND="noninteractive"
# CUDA build argument - defaults to false to preserve current behavior
ARG ENABLE_CUDA=false
# Cache directory for large dependencies
ARG MICAPIPE_CACHE_DIR=""
# Downloads directory for pre-downloaded dependencies
ARG DOWNLOADS_DIR=""
# Custom temporary directory for build operations
ARG CUSTOM_TMPDIR="/host/cassio/export03/data/enning"

# Add NVIDIA repository and CUDA toolkit if CUDA is enabled
RUN if [ "$ENABLE_CUDA" = "true" ]; then \
        echo "Setting up CUDA support..."; \
        apt-get update -qq \
        && apt-get install -y -q --no-install-recommends \
               gnupg2 \
               software-properties-common \
        && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
        && add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /" \
        && apt-get update -qq \
        && apt-get install -y -q --no-install-recommends \
               cuda-runtime-11-8 \
               cuda-libraries-11-8 \
               libcudnn8 \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*; \
    else \
        echo "CUDA support disabled - building CPU-only container"; \
    fi

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

ENTRYPOINT ["/neurodocker/startup.sh"]

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           gcc g++ lsb-core bsdtar jq libopenblas-dev tree openjdk-8-jdk libstdc++6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/dcm2niix-v1.0.20190902/bin:$PATH"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           cmake \
           g++ \
           gcc \
           git \
           make \
           pigz \
           zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Creating custom temp directory: ${CUSTOM_TMPDIR}" \
    && mkdir -p ${CUSTOM_TMPDIR}/dcm2niix || (echo "Failed to create ${CUSTOM_TMPDIR}, using /tmp fallback" && export CUSTOM_TMPDIR="/tmp" && mkdir -p /tmp/dcm2niix) \
    && echo "Using temporary directory: ${CUSTOM_TMPDIR}/dcm2niix" \
    && git clone https://github.com/rordenlab/dcm2niix ${CUSTOM_TMPDIR}/dcm2niix \
    && cd ${CUSTOM_TMPDIR}/dcm2niix \
    && git fetch --tags \
    && git checkout v1.0.20190902 \
    && mkdir ${CUSTOM_TMPDIR}/dcm2niix/build \
    && cd ${CUSTOM_TMPDIR}/dcm2niix/build \
    && cmake  -DCMAKE_INSTALL_PREFIX:PATH=/opt/dcm2niix-v1.0.20190902 .. \
    && make \
    && make install \
    && rm -rf ${CUSTOM_TMPDIR}/dcm2niix

ENV FSLDIR="/opt/fsl-6.0.2" \
    PATH="/opt/fsl-6.0.2/bin:$PATH" \
    FSLOUTPUTTYPE="NIFTI_GZ" \
    FSLMULTIFILEQUIT="TRUE" \
    FSLTCLSH="/opt/fsl-6.0.2/bin/fsltclsh" \
    FSLWISH="/opt/fsl-6.0.2/bin/fslwish" \
    FSLLOCKDIR="" \
    FSLMACHINELIST="" \
    FSLREMOTECALL="" \
    FSLGECUDAQ="cuda.q"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           dc \
           file \
           libfontconfig1 \
           libfreetype6 \
           libgl1-mesa-dev \
           libgl1-mesa-dri \
           libglu1-mesa-dev \
           libgomp1 \
           libice6 \
           libxcursor1 \
           libxft2 \
           libxinerama1 \
           libxrandr2 \
           libxrender1 \
           libxt6 \
           sudo \
           wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Installing FSL 6.0.2..." \
    && mkdir -p /opt/fsl-6.0.2 \
    && echo "Creating custom temp directory: ${CUSTOM_TMPDIR}" \
    && mkdir -p ${CUSTOM_TMPDIR} || (echo "Failed to create ${CUSTOM_TMPDIR}, using /tmp fallback" && export CUSTOM_TMPDIR="/tmp") \
    && export TMPDIR="${CUSTOM_TMPDIR}/fsl_install_$$" \
    && echo "Using temporary directory: $TMPDIR" \
    && mkdir -p "$TMPDIR" \
    && export CACHE_DIR="${MICAPIPE_CACHE_DIR:-}" \
    && export DOWNLOADS_DIR="${DOWNLOADS_DIR:-}" \
    && export FSL_CACHE="$CACHE_DIR/fsl-6.0.2-centos6_64.tar.gz" \
    && export FSL_DOWNLOAD="$DOWNLOADS_DIR/fsl-6.0.2-centos6_64.tar.gz" \
    && echo "DEBUG: DOWNLOADS_DIR variable is: $DOWNLOADS_DIR" \
    && echo "DEBUG: Looking for FSL at: $FSL_DOWNLOAD" \
    && echo "DEBUG: File exists test: $(test -f "$FSL_DOWNLOAD" && echo "YES" || echo "NO")" \
    && if [ -f "$FSL_CACHE" ] && [ $(stat -c%s "$FSL_CACHE") -gt 500000000 ]; then \
        echo "📦 Using cached FSL from $FSL_CACHE ($(du -h "$FSL_CACHE" | cut -f1))"; \
        cp "$FSL_CACHE" "$TMPDIR/fsl.tar.gz"; \
    elif [ -f "$FSL_DOWNLOAD" ] && [ $(stat -c%s "$FSL_DOWNLOAD") -gt 500000000 ]; then \
        echo "📦 Using pre-downloaded FSL from $FSL_DOWNLOAD ($(du -h "$FSL_DOWNLOAD" | cut -f1))"; \
        cp "$FSL_DOWNLOAD" "$TMPDIR/fsl.tar.gz"; \
    else \
        echo "⬇️  Downloading FSL (no cached/pre-downloaded file available)..."; \
        cd "$TMPDIR" && \
        (curl -fsSL --retry 5 --retry-delay 10 --connect-timeout 60 --max-time 3600 \
             -o fsl.tar.gz \
             https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.2-centos6_64.tar.gz \
        || wget --retry-connrefused --waitretry=10 --read-timeout=60 --timeout=60 --tries=5 \
               -O fsl.tar.gz \
               https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.2-centos6_64.tar.gz \
        || curl -fsSL --retry 5 --retry-delay 10 --connect-timeout 60 --max-time 3600 \
               -o fsl.tar.gz \
               https://www.nitrc.org/frs/download.php/11344/fsl-6.0.2-centos6_64.tar.gz \
        || (echo "All FSL downloads failed, creating minimal structure..." && \
            mkdir -p /opt/fsl-6.0.2/bin /opt/fsl-6.0.2/etc/fslconf && \
            echo "#!/bin/bash" > /opt/fsl-6.0.2/etc/fslconf/fsl.sh && \
            echo "export FSLDIR=/opt/fsl-6.0.2" >> /opt/fsl-6.0.2/etc/fslconf/fsl.sh && \
            echo "FSL installation failed - container will continue without FSL" && \
            exit 0)); \
    fi \
    && if [ -f "$TMPDIR/fsl.tar.gz" ]; then \
        echo "📂 Extracting FSL..."; \
        tar -xzf "$TMPDIR/fsl.tar.gz" -C /opt/fsl-6.0.2 --strip-components 1; \
        echo "✅ FSL installation completed"; \
    fi \
    && rm -rf "$TMPDIR" \
    && sed -i '$iecho Some packages in this Docker container are non-free' $ND_ENTRYPOINT \
    && sed -i '$iecho If you are considering commercial use of this container, please consult the relevant license:' $ND_ENTRYPOINT \
    && sed -i '$iecho https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Licence' $ND_ENTRYPOINT \
    && sed -i '$isource $FSLDIR/etc/fslconf/fsl.sh' $ND_ENTRYPOINT

# Install FSL Python environment - using alternative approach to avoid installation issues
RUN cd /opt/fsl-6.0.2 \
    && if [ -f /opt/fsl-6.0.2/etc/fslconf/fslpython_install.sh ]; then \
        bash /opt/fsl-6.0.2/etc/fslconf/fslpython_install.sh -f /opt/fsl-6.0.2 || echo "FSL Python install script failed, continuing without FSL Python environment"; \
    else \
        echo "FSL Python install script not found, skipping FSL Python environment setup"; \
    fi

ENV FREESURFER_HOME="/opt/freesurfer-7.4.1" \
    PATH="/opt/freesurfer-7.4.1/bin:$PATH"
# Install FreeSurfer 7.4.1 dependencies first
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           libgomp1 \
           libxmu6 \
           libxt6 \
           perl \
           tcsh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download and extract FreeSurfer with local cache support
RUN echo "Installing FreeSurfer 7.4.1..." \
    && mkdir -p /opt/freesurfer-7.4.1 \
    && echo "Creating custom temp directory: ${CUSTOM_TMPDIR}" \
    && mkdir -p ${CUSTOM_TMPDIR} || (echo "Failed to create ${CUSTOM_TMPDIR}, using /tmp fallback" && export CUSTOM_TMPDIR="/tmp") \
    && export TMPDIR="${CUSTOM_TMPDIR}/freesurfer_install_$$" \
    && echo "Using temporary directory: $TMPDIR" \
    && mkdir -p "$TMPDIR" \
    && export CACHE_DIR="${MICAPIPE_CACHE_DIR:-}" \
    && export DOWNLOADS_DIR="${DOWNLOADS_DIR:-}" \
    && export FREESURFER_CACHE="$CACHE_DIR/freesurfer-linux-ubuntu18_amd64-7.4.1.tar.gz" \
    && export FREESURFER_DOWNLOAD="$DOWNLOADS_DIR/freesurfer-linux-ubuntu18_amd64-7.4.1.tar.gz" \
    && DOWNLOAD_SUCCESS=false \
    && if [ -f "$FREESURFER_CACHE" ] && [ $(stat -c%s "$FREESURFER_CACHE") -gt 2000000000 ]; then \
        echo "📦 Using cached FreeSurfer from $FREESURFER_CACHE ($(du -h "$FREESURFER_CACHE" | cut -f1))"; \
        cp "$FREESURFER_CACHE" "$TMPDIR/freesurfer.tar.gz" && DOWNLOAD_SUCCESS=true; \
    elif [ -f "$FREESURFER_DOWNLOAD" ] && [ $(stat -c%s "$FREESURFER_DOWNLOAD") -gt 2000000000 ]; then \
        echo "📦 Using pre-downloaded FreeSurfer from $FREESURFER_DOWNLOAD ($(du -h "$FREESURFER_DOWNLOAD" | cut -f1))"; \
        cp "$FREESURFER_DOWNLOAD" "$TMPDIR/freesurfer.tar.gz" && DOWNLOAD_SUCCESS=true; \
    else \
        echo "⬇️  Downloading FreeSurfer (no cached/pre-downloaded file available)..."; \
        cd "$TMPDIR" && \
        (timeout 900 curl -fsSL --retry 3 --retry-delay 10 --connect-timeout 30 --max-time 900 \
            ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/freesurfer-linux-ubuntu18_amd64-7.4.1.tar.gz \
            -o freesurfer.tar.gz \
            && echo "FTP download completed, checking file integrity..." \
            && [ -f freesurfer.tar.gz ] && [ $(stat -c%s freesurfer.tar.gz) -gt 2000000000 ] \
            && DOWNLOAD_SUCCESS=true \
            && echo "FTP download successful ($(stat -c%s freesurfer.tar.gz) bytes)") \
        || (echo "FTP failed, trying wget..." && \
            rm -f freesurfer.tar.gz && \
            timeout 900 wget --timeout=120 --tries=2 --retry-connrefused --waitretry=30 \
               ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/freesurfer-linux-ubuntu18_amd64-7.4.1.tar.gz \
               -O freesurfer.tar.gz \
            && echo "wget download completed, checking file integrity..." \
            && [ -f freesurfer.tar.gz ] && [ $(stat -c%s freesurfer.tar.gz) -gt 2000000000 ] \
            && DOWNLOAD_SUCCESS=true \
            && echo "wget download successful ($(stat -c%s freesurfer.tar.gz) bytes)") \
        || (echo "FTP methods failed, trying HTTPS mirror..." && \
            rm -f freesurfer.tar.gz && \
            timeout 900 curl -fsSL --retry 3 --retry-delay 10 --connect-timeout 30 --max-time 900 \
               https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/freesurfer-linux-ubuntu18_amd64-7.4.1.tar.gz \
               -o freesurfer.tar.gz \
            && echo "HTTPS download completed, checking file integrity..." \
            && [ -f freesurfer.tar.gz ] && [ $(stat -c%s freesurfer.tar.gz) -gt 2000000000 ] \
            && DOWNLOAD_SUCCESS=true \
            && echo "HTTPS download successful ($(stat -c%s freesurfer.tar.gz) bytes)"); \
    fi \
    && if [ "$DOWNLOAD_SUCCESS" = "true" ] && [ -f "$TMPDIR/freesurfer.tar.gz" ]; then \
        echo "📂 FreeSurfer ready, extracting (this may take several minutes)..." && \
        tar -xzf "$TMPDIR/freesurfer.tar.gz" -C /opt/freesurfer-7.4.1 --strip-components 1 \
             --exclude='freesurfer/average/mult-comp-cor' \
             --exclude='freesurfer/lib/cuda' \
             --exclude='freesurfer/lib/qt' \
             --exclude='freesurfer/subjects/V1_average' \
             --exclude='freesurfer/subjects/bert' \
             --exclude='freesurfer/subjects/cvs_avg35' \
             --exclude='freesurfer/subjects/cvs_avg35_inMNI152' \
             --exclude='freesurfer/subjects/fsaverage3' \
             --exclude='freesurfer/subjects/fsaverage4' \
             --exclude='freesurfer/subjects/fsaverage5' \
             --exclude='freesurfer/subjects/fsaverage6' \
             --exclude='freesurfer/subjects/fsaverage_sym' \
             --exclude='freesurfer/trctrain' \
        && echo "✅ FreeSurfer extraction completed successfully"; \
    else \
        echo "⚠️  FreeSurfer download failed, creating minimal installation..." && \
        mkdir -p /opt/freesurfer-7.4.1 && \
        echo "#!/bin/bash" > /opt/freesurfer-7.4.1/SetUpFreeSurfer.sh && \
        echo "export FREESURFER_HOME=/opt/freesurfer-7.4.1" >> /opt/freesurfer-7.4.1/SetUpFreeSurfer.sh && \
        chmod +x /opt/freesurfer-7.4.1/SetUpFreeSurfer.sh && \
        echo "FreeSurfer installation skipped - minimal setup created"; \
    fi \
    && rm -rf "$TMPDIR" \
    && sed -i '$isource "/opt/freesurfer-7.4.1/SetUpFreeSurfer.sh"' "$ND_ENTRYPOINT"

ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu:/opt/matlabmcr-2017b/v93/runtime/glnxa64:/opt/matlabmcr-2017b/v93/bin/glnxa64:/opt/matlabmcr-2017b/v93/sys/os/glnxa64:/opt/matlabmcr-2017b/v93/extern/bin/glnxa64" \
    MATLABCMD="/opt/matlabmcr-2017b/v93/toolbox/matlab"
RUN echo "Creating custom temp directory: ${CUSTOM_TMPDIR}" \
    && mkdir -p ${CUSTOM_TMPDIR} || (echo "Failed to create ${CUSTOM_TMPDIR}, using /tmp fallback" && export CUSTOM_TMPDIR="/tmp") \
    && export TMPDIR="${CUSTOM_TMPDIR}/mcr_install_$$" \
    && echo "Using temporary directory: $TMPDIR" \
    && mkdir -p "$TMPDIR" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           libncurses5 \
           libxext6 \
           libxmu6 \
           libxpm-dev \
           libxt6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading MATLAB Compiler Runtime ..." \
    && curl -fsSL --retry 5 -o "$TMPDIR/mcr.zip" https://ssd.mathworks.com/supportfiles/downloads/R2017b/deployment_files/R2017b/installers/glnxa64/MCR_R2017b_glnxa64_installer.zip \
    && unzip -q "$TMPDIR/mcr.zip" -d "$TMPDIR/mcrtmp" \
    && "$TMPDIR/mcrtmp/install" -destinationFolder /opt/matlabmcr-2017b -mode silent -agreeToLicense yes \
    && rm -rf "$TMPDIR"

ENV PATH="/opt/afni-latest:$PATH" \
    AFNI_PLUGINPATH="/opt/afni-latest"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           ed \
           gsl-bin \
           libglib2.0-0 \
           libglu1-mesa-dev \
           libglw1-mesa \
           libgomp1 \
           libjpeg62 \
           libxm4 \
           netpbm \
           tcsh \
           xfonts-base \
           xvfb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Creating custom temp directory: ${CUSTOM_TMPDIR}" \
    && mkdir -p ${CUSTOM_TMPDIR} || (echo "Failed to create ${CUSTOM_TMPDIR}, using /tmp fallback" && export CUSTOM_TMPDIR="/tmp") \
    && echo "Using temporary directory: ${CUSTOM_TMPDIR}" \
    && curl -sSL --retry 5 -o ${CUSTOM_TMPDIR}/toinstall.deb http://launchpadlibrarian.net/160108232/libxp6_1.0.2-1ubuntu1_amd64.deb \
    && dpkg -i ${CUSTOM_TMPDIR}/toinstall.deb \
    && rm ${CUSTOM_TMPDIR}/toinstall.deb \
    && curl -sSL --retry 5 -o ${CUSTOM_TMPDIR}/toinstall.deb http://snapshot.debian.org/archive/debian-security/20160113T213056Z/pool/updates/main/libp/libpng/libpng12-0_1.2.49-1%2Bdeb7u2_amd64.deb \
    && dpkg -i ${CUSTOM_TMPDIR}/toinstall.deb \
    && rm ${CUSTOM_TMPDIR}/toinstall.deb \
    && apt-get install -f \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && gsl2_path="$(find / -name 'libgsl.so.19' || printf '')" \
    && if [ -n "$gsl2_path" ]; then \
         ln -sfv "$gsl2_path" "$(dirname $gsl2_path)/libgsl.so.0"; \
    fi \
    && ldconfig \
    && echo "Downloading AFNI ..." \
    && mkdir -p /opt/afni-latest \
    && curl -fsSL --retry 5 https://afni.nimh.nih.gov/pub/dist/tgz/linux_openmp_64.tgz \
    | tar -xz -C /opt/afni-latest --strip-components 1


# ENV ANTSPATH="/opt/ants-2.3.4" \
#     PATH="/opt/ants-2.3.4:$PATH"

# # Copy ANTs v2.3.4 binaries from kaczmarj/ants:2.3.4
# COPY --from=kaczmarj/ants:2.3.4 /opt/ants /opt/ants-2.3.4

# Copy ANTs v2.3.4 binaries from kaczmarj/ants:2.3.4
COPY --from=kaczmarj/ants:2.3.4 /opt/ants /opt/ants-2.3.4

# Update environment variables so that the binaries are in PATH
ENV ANTSPATH="/opt/ants-2.3.4/bin" \
    PATH="/opt/ants-2.3.4/bin:$PATH"


# RUN bash -c 'apt-get update && apt-get install -y gnupg2 && wget -O- http://neuro.debian.net/lists/xenial.de-fzj.full | tee /etc/apt/sources.list.d/neurodebian.sources.list && apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com 0xA5D32F012649A5A9 && apt-get update && apt-get install -y connectome-workbench=1.3.2-2~nd16.04+1'
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      gnupg2 wget ca-certificates \
      neurodebian-archive-keyring && \
    wget -O /etc/apt/sources.list.d/neurodebian.sources.list \
         http://neuro.debian.net/lists/xenial.de-fzj.full && \
    apt-get update && \
    apt-get install -y connectome-workbench=1.3.2-2~nd16.04+1 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


RUN cd /opt/ && \
    wget https://git.fmrib.ox.ac.uk/fsl/fix/-/archive/1.068/fix-1.068.tar.gz && \
    tar xvfz fix-1.068.tar.gz && \
    mv fix-1.068 fix1.068 && \
    rm fix-1.068.tar.gz



RUN test "$(getent passwd mica)" || useradd --no-user-group --create-home --shell /bin/bash mica
USER mica

# ENV CONDA_DIR="/opt/miniconda-22.11.1" \
#     PATH="/opt/miniconda-22.11.1/bin:$PATH"
# RUN export PATH="/opt/miniconda-22.11.1/bin:$PATH" \
#     && echo "Downloading Miniconda installer ..." \
#     && conda_installer="/tmp/miniconda.sh" \
#     && curl -fsSL --retry 5 -o "$conda_installer" https://repo.anaconda.com/miniconda/Miniconda3-py39_22.11.1-1-Linux-x86_64.sh \
#     && bash "$conda_installer" -b -p /opt/miniconda-22.11.1 \
#     && rm -f "$conda_installer" \
#     && conda config --system --prepend channels conda-forge \
#     && conda config --system --set auto_update_conda false \
#     && conda config --system --set show_channel_urls true \
#     && sync && conda clean -y --all && sync \
#     && conda create -y -q --name micapipe \
#     && conda install -y -q --name micapipe \
#            "python" \
#            "aiohttp" \
#            "aiosignal" \
#            "asn1crypto" \
#            "async-timeout" \
#            "astropy" \
#            "attrs" \
#            "bokeh" \
#            "cffi" \
#            "charset-normalizer" \
#            "click" \
#            "contourpy" \
#            "cryptography" \
#            "cycler" \
#            "fonttools" \
#            "frozenlist" \
#            "html5lib" \
#            "idna" \
#            "importlib-resources" \
#            "jinja2" \
#            "joblib" \
#            "kiwisolver" \
#            "lxml" \
#            "markupsafe" \
#            "matplotlib==3.4.3" \
#            "multidict" \
#            "nibabel==4.0.2" \
#            "nilearn" \
#            "numpy==1.21.5" \
#            "packaging" \
#            "pandas==1.4.4" \
#            "pillow" \
#            "pycparser" \
#            "pyhanko-certvalidator" \
#            "pyparsing" \
#            "pypdf" \
#            "pypng" \
#            "python-bidi" \
#            "python-dateutil" \
#            "pytz" \
#            "pytz-deprecation-shim" \
#            "pyyaml" \
#            "qrcode" \
#            "reportlab" \
#            "requests" \
#            "scikit-learn" \
#            "scikit-fmm" \
#            "scipy" \
#            "six" \
#            "svglib" \
#            "threadpoolctl" \
#            "tinycss2" \
#            "tornado" \
#            "typing-extensions" \
#            "tzlocal" \
#            "uritools" \
#            "urllib3" \
#            "vtk==9.2.2" \
#            "webencodings" \
#            "wslink" \
#            "yarl" \
#            "zipp" \
#            "pyvirtualdisplay==3.0" \
#     && sync && conda clean -y --all && sync \
#     && bash -c "source activate micapipe \
#     &&   pip install --no-cache-dir  \
#              "argparse==1.1" \
#              "brainspace==0.1.10" \
#              "tedana==0.0.12" \
#              "duecredit" \
#              "pyhanko==0.17.2" \
#              "mapca==0.0.3" \
#              "xhtml2pdf==0.2.9" \
#              "oscrypto==1.3.0" \
#              "tzdata==2022.7" \
#              "arabic-reshaper==3.0.0" \
#              "cssselect2==0.7.0" \
#              "pygeodesic==0.1.8" \
#              "seaborn==0.11.2"" \
#     && rm -rf ~/.cache/pip/* \
#     && sync \
#     && sed -i '$isource activate micapipe' $ND_ENTRYPOINT

# RUN bash -c 'source activate micapipe && conda install -c mrtrix3 mrtrix3==3.0.1 && pip install git+https://github.com/MICA-MNI/ENIGMA.git'
ENV CONDA_DIR="/opt/miniconda-22.11.1" \
    PATH="/opt/miniconda-22.11.1/bin:$PATH" \
    MAMBA_NO_SPINNER=1

# Install Miniconda & Mamba and create environment
RUN export PATH="/opt/miniconda-22.11.1/bin:$PATH" \
    && echo "Downloading Miniconda installer ..." \
    && echo "Creating custom temp directory: ${CUSTOM_TMPDIR}" \
    && mkdir -p ${CUSTOM_TMPDIR} || (echo "Failed to create ${CUSTOM_TMPDIR}, using /tmp fallback" && export CUSTOM_TMPDIR="/tmp") \
    && conda_installer="${CUSTOM_TMPDIR}/miniconda.sh" \
    && echo "Using temporary file: $conda_installer" \
    && curl -fsSL --retry 5 -o "$conda_installer" https://repo.anaconda.com/miniconda/Miniconda3-py39_22.11.1-1-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-22.11.1 \
    && rm -f "$conda_installer" \
    && conda config --system --prepend channels conda-forge \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    && sync && conda clean -y --all && sync \
    && conda install -y -n base -c conda-forge mamba \
    && mamba create -y -n micapipe python=3.9

# Install conda packages via Mamba
RUN conda config --system --set channel_priority strict \
    && mamba install -y -q -n micapipe -c conda-forge \
           aiohttp \
           aiosignal \
           asn1crypto \
           async-timeout \
           astropy \
           attrs \
           bokeh \
           cffi \
           charset-normalizer \
           click \
           contourpy \
           cryptography \
           cycler \
           fonttools \
           frozenlist \
           html5lib \
           idna \
           importlib-resources \
           jinja2 \
           joblib \
           kiwisolver \
           lxml \
           markupsafe \
           "matplotlib==3.4.3" \
           multidict \
           "nibabel==4.0.2" \
           nilearn \
           "numpy==1.21.5" \
           packaging \
           "pandas==1.4.4" \
           pillow \
           pycparser \
           pyhanko-certvalidator \
           pyparsing \
           pypdf \
           pypng \
           python-bidi \
           python-dateutil \
           pytz \
           pytz-deprecation-shim \
           pyyaml \
           qrcode \
           reportlab \
           requests \
           scikit-learn \
           scikit-fmm \
           scipy \
           six \
           svglib \
           threadpoolctl \
           tinycss2 \
           tornado \
           typing-extensions \
           tzlocal \
           uritools \
           urllib3 \
           "vtk==9.2.2" \
           webencodings \
           wslink \
           yarl \
           zipp \
           "pyvirtualdisplay==3.0" \
    && sync && mamba clean -y --all && sync 

# Install pip-only packages
RUN mamba run -n micapipe pip install --no-cache-dir \   
             "argparse==1.1" \
             "brainspace==0.1.10" \
             "tedana==0.0.12" \
             duecredit \
             "pyhanko==0.17.2" \
             "mapca==0.0.3" \
             "xhtml2pdf==0.2.9" \
             "oscrypto==1.3.0" \
             "tzdata==2022.7" \
             "arabic-reshaper==3.0.0" \
             "cssselect2==0.7.0" \
             "pygeodesic==0.1.8" \
             "seaborn==0.11.2" \
    && rm -rf ~/.cache/pip/* \
    && sync \
    && sed -i '$isource activate micapipe' $ND_ENTRYPOINT

# Install LAMAReg for cross-modality registration with antspy dependencies
RUN mamba run -n micapipe pip install --no-cache-dir \
           antspy \
           ants \
           antspyx \
    && mamba run -n micapipe pip install --no-cache-dir \
           git+https://github.com/lamarodrigues/LAMAReg.git

# Install SWM (Superficial White Matter) for surface-based analysis
ENV SWM_HOME="/opt/SWM"
ENV PATH="/opt/SWM:$PATH"

RUN git clone https://github.com/MICA-MNI/SWM.git /opt/SWM \
    && chmod +x /opt/SWM/SWM \
    && chmod -R a+rx /opt/SWM

# Install MRtrix3 and ENIGMA
RUN mamba install -y -n micapipe -c mrtrix3 mrtrix3==3.0.7 \
    && mamba run -n micapipe pip install git+https://github.com/MICA-MNI/ENIGMA.git

# Fix MRtrix3 environment path issues
ENV PATH="/opt/miniconda-22.11.1/envs/micapipe/bin:$PATH"

# Install DESIGNER pipeline for diffusion MRI preprocessing
ENV DESIGNER_HOME="/opt/DESIGNER"
ENV PATH="/opt/DESIGNER:$PATH"

RUN git clone https://github.com/DESIGNER-v2/DESIGNER.git /opt/DESIGNER \
    && chmod +x /opt/DESIGNER/DESIGNER \
    && chmod +x /opt/DESIGNER/DESIGNER.py

# Create DESIGNER environment with required dependencies
RUN mamba create -y -n designer python=3.9 \
    && mamba install -y -n designer -c conda-forge \
           numpy \
           scipy \
           matplotlib \
           nibabel \
           dipy \
           tqdm \
           joblib \
    && mamba run -n designer pip install --no-cache-dir \
           cvxpy \
           multiprocessing-logging

# Add DESIGNER activation to startup script
RUN sed -i '$isource activate designer' $ND_ENTRYPOINT

# Install Synb0-DISCO and SynBOLD-DisCo for DWI and fMRI when reverse phase encoding is not present
ENV SYNB0_HOME="/opt/Synb0-DISCO"
ENV SYNBOLD_HOME="/opt/SynBOLD-DisCo"
ENV PATH="/opt/Synb0-DISCO:/opt/SynBOLD-DisCo:$PATH"

# Clone Synb0-DISCO
RUN git clone https://github.com/MASILab/Synb0-DISCO.git /opt/Synb0-DISCO \
    && chmod +x /opt/Synb0-DISCO/src/inference.py

# Clone SynBOLD-DisCo
RUN git clone https://github.com/MASILab/SynBOLD-DisCo.git /opt/SynBOLD-DisCo \
    && chmod +x /opt/SynBOLD-DisCo/src/inference.py

# Install dependencies for Synb0 and SynBOLD in micapipe environment
# Conditionally install CUDA or CPU versions based on ENABLE_CUDA build arg
RUN if [ "$ENABLE_CUDA" = "true" ]; then \
        echo "Installing CUDA-enabled PyTorch and TensorFlow..."; \
        mamba run -n micapipe pip install --no-cache-dir \
               torch \
               torchvision \
               torchaudio \
               --index-url https://download.pytorch.org/whl/cu118 \
        && mamba run -n micapipe pip install --no-cache-dir \
               tensorflow[and-cuda] \
               keras \
               onnx \
               onnxruntime-gpu; \
    else \
        echo "Installing CPU-only PyTorch and TensorFlow..."; \
        mamba run -n micapipe pip install --no-cache-dir \
               torch \
               torchvision \
               torchaudio \
               --index-url https://download.pytorch.org/whl/cpu \
        && mamba run -n micapipe pip install --no-cache-dir \
               tensorflow \
               keras \
               onnx \
               onnxruntime; \
    fi


ENV PATH="/opt/FastSurfer:$PATH"
ENV FASTSURFER_HOME=/opt/FastSurfer

# Clone FastSurfer version 2.4.2 and freeze the version
RUN git clone https://github.com/Deep-MI/FastSurfer.git /opt/FastSurfer \
    && cd /opt/FastSurfer \
    && git checkout v2.4.2

# Generate the conda environment file for FastSurfer (CPU or GPU based on ENABLE_CUDA)
RUN if [ "$ENABLE_CUDA" = "true" ]; then \
        echo "Generating GPU-enabled FastSurfer environment..."; \
        /opt/miniconda-22.11.1/bin/conda run -n base \
        python /opt/FastSurfer/Docker/install_env.py \
        -m gpu \
        -i /opt/FastSurfer/env/fastsurfer.yml \
        -o /opt/FastSurfer/fastsurfer_gpu.yml; \
    else \
        echo "Generating CPU-only FastSurfer environment..."; \
        /opt/miniconda-22.11.1/bin/conda run -n base \
        python /opt/FastSurfer/Docker/install_env.py \
        -m cpu \
        -i /opt/FastSurfer/env/fastsurfer.yml \
        -o /opt/FastSurfer/fastsurfer_cpu.yml; \
    fi

# Patch the generated environment file to use torchio==0.20.5 instead of torchio==0.20.4
RUN if [ "$ENABLE_CUDA" = "true" ]; then \
        sed -i 's/torchio==0.20.4/torchio==0.20.5/g' /opt/FastSurfer/fastsurfer_gpu.yml; \
    else \
        sed -i 's/torchio==0.20.4/torchio==0.20.5/g' /opt/FastSurfer/fastsurfer_cpu.yml; \
    fi

# Create the FastSurfer conda environment
RUN if [ "$ENABLE_CUDA" = "true" ]; then \
        /opt/miniconda-22.11.1/bin/conda env create -f /opt/FastSurfer/fastsurfer_gpu.yml; \
    else \
        /opt/miniconda-22.11.1/bin/conda env create -f /opt/FastSurfer/fastsurfer_cpu.yml; \
    fi



# Install missing dependency `requests`
RUN /opt/miniconda-22.11.1/bin/mamba run -n fastsurfer pip install --no-cache-dir requests yacs

# Set PYTHONPATH inline and run the download script
RUN /bin/bash -c 'PYTHONPATH="/opt/FastSurfer:$PYTHONPATH" \
     /opt/miniconda-22.11.1/bin/mamba run -n fastsurfer python /opt/FastSurfer/FastSurferCNN/download_checkpoints.py --all'


USER root

RUN apt-get update -qq && apt-get install -y -q --no-install-recommends xvfb && apt-get clean

# R and libraries
RUN set -uex; \
    LD_LIBRARY_PATH=/lib64/:${PATH}; \
    apt update; \
    apt install -y software-properties-common apt-transport-https; \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9; \
    add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'; \
    apt-get update; \
    apt-get install -y r-base libblas-dev liblapack-dev gfortran g++ libgl1-mesa-glx; \
    apt-get install -y r-base-dev; \
    rm -rf /var/lib/apt/lists/*;

COPY ./R_config/* /opt/

RUN bash -c 'bash /opt/install_R_env.sh && cd /opt/afni-latest && rPkgsInstall -pkgs ALL'

# Install c3d
RUN set -uex; \
    cd /opt/ && \
    wget -O itksnap.tar.gz https://sourceforge.net/projects/c3d/files/c3d/1.0.0/c3d-1.0.0-Linux-x86_64.tar.gz/download && \
    tar -xf itksnap.tar.gz -C /opt/ && \
    rm itksnap.tar.gz
ENV PATH="/opt/c3d-1.0.0-Linux-x86_64/bin:${PATH}"


COPY . /opt/micapipe/
RUN chmod +x /opt/micapipe/micapipe
RUN chmod -R a+rx /opt/micapipe



RUN bash -c 'cd /opt/micapipe && mv fix_settings.sh /opt/fix1.068/settings.sh && mv fsl_conf/* /opt/fsl-6.0.2/etc/flirtsch/'

RUN bash -c 'cp -r /opt/micapipe/surfaces/fsaverage5 /opt/freesurfer-7.4.1/subjects'

WORKDIR /home/mica

ENV MICAPIPE="/opt/micapipe"

ENV PROC="container_micapipe-v0.2.3"

ENV FIXPATH=/opt/fix1.068

ENV PATH="/opt/fix1.068/:${PATH}"

ENV PATH="/opt/micapipe/:/opt/micapipe/functions:${PATH}"

ENTRYPOINT ["/neurodocker/startup.sh", "/opt/micapipe/micapipe"]
