#!/bin/bash
#
# MICA BIDS structural processing
#---------------- FUNCTION: HELP ----------------#
help() {
echo -e "\033[38;5;141m
Usage:    `basename $0`\033[0m  \033[38;5;197m-sub\033[0m <subject_id> \033[38;5;197m-out\033[0m <FULL_PATH/outputDirectory> \033[38;5;197m-bids\033[0m <FULL_PATH/BIDS-directory>\n
\t\t\033[38;5;197m-sub\033[0m 	Subject identification (no 'sub-')
\t\t\033[38;5;197m-bids\033[0m 	Path to BIDS directory
\t\t\033[38;5;197m-out\033[0m 	Output directory for the processed files <derivatives>.
\t\t\033[38;5;197m-force\033[0m 	WARNING this will overwrites the subject directory.
\t\t\033[38;5;197m-quiet\033[0m 	Does NOT print comments
\t\t\033[38;5;197m-micaq\033[0m 	ONLY for MICA local processing

Flags for processing:
    -all              : Performs all stages of structural processing
    -proc_volumetric  : Volumetric processing
    -proc_freesurfer  : Freesurfer recon-all processing
    -proc_dwi         : DWI-Diffusion weighted images processing with MRtrix3
    -proc_rsfmri      : Resting state Funtional MRI processing

    -post_dwi         : DWI-Diffusion weighted images processing with MRtrix3
                        (REQUIRES -proc_dwi)
    -post_structural  : Post structural volumetric processing
                        (REQUIRES -proc_volumetric and -proc_freesurfer)

    -proc_surfpatch   : Surfpatch hippocampal subfields processing
                        (REQUIRES -micaq)

Software versions:
  Freesurfer  6.0   (https://surfer.nmr.mgh.harvard.edu/)
  FSL         6.0   (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki)
  AFNI        1.10  (https://afni.nimh.nih.gov/download)
  MRtrix3     3.0.0 (https://www.mrtrix.org)
  ANTs        2.3.3 (https://github.com/ANTsX/ANTs)

McGill University, MNI, MICA-lab, May 2020
Written by Reinder Vos de Wael
Edited by RRC
https://github.com/MICA-MNI
http://mica-mni.github.io/
"
}

# Chek MICASOFT_DIR
if [ -z "${MICASOFT_DIR}" ]; then
echo -e "\033[38;5;1m\n---------------------------------------------------------\n
[ERROR]... MICASOFT_DIR must be define in your enviroment\033[0m
           TRY: export MICASOFT_DIR=<github_Directory>/micasoft\n
\033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 0
fi

if [ ! -f ${MICASOFT_DIR}/pipelines/09_bids_micaProcessing/utilities.sh ]; then
echo -e "\033[38;5;1m\n---------------------------------------------------------\n
[ERROR]... MICASOFT_DIR is defined but the PATH is wrong,
           it should match /micasoft directory\033[0m
           CHECK PATH to MICASOFT_DIR:
           $MICASOFT_DIR\n
\033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 0
fi
# Source print functions from MICASOFT_DIR
source $MICASOFT_DIR/pipelines/09_bids_micaProcessing/utilities.sh
source $MICASOFT_DIR/pipelines/08_micaProcessing/mica_processingSupportFunctions.sh


Title "BIDS >> MICA processing >> proc_struct \n\t\tSubject: $id"

#------------------------------------------------------------------------------#
#			ARGUMENTS
# Create VARIABLES
for arg in "$@"
do
  case "$arg" in
  -h|-help)
    help
    exit 1
  ;;
  -sub)
   id=$2
   shift;shift
  ;;
  -out)
   out=$2
   shift;shift
  ;;
  -bids)
   BIDS=$2
   shift;shift
  ;;
  -all)
   proc=TRUE
   shift
  ;;
  -proc_volumetric)
   proc1=TRUE
   shift
  ;;
  -proc_freesurfer)
   proc2=TRUE
   shift
  ;;
  -post_structural)
  post1=TRUE
  shift
 ;;
  -micaq)
   micaq=$2
   shift;shift
  ;;
  -MICs)
   MICs=$2
   shift;shift
  ;;
  -force)
   force=TRUE
   shift
  ;;
  -quiet)
   quiet=TRUE
   shift
  ;;
  -*)
   Error "Unknown option ${2}"
   help
   exit
  ;;
   esac
done

# argument check out & WARNINGS
arg=($id $out $BIDS)
if [ "${#arg[@]}" -lt 3 ]; then
Error "One or more mandatory arguments are missing:"
Note "-sub " $id
Note "-out " "$out"
Note "-bids " "$BIDS"
help; exit 0; fi
runs=($proc $proc1 $proc2 $proc2)
if [ "${#runs[@]}" -lt 1 ]; then
Error "Processing flag is missing:
                    -all
                    -proc_volumetric
                    -proc_freesurfer
                    -proc_surfpatch"
help; exit 0; fi

# Get the real path of the Inputs
out=`realpath $out`
BIDS=`realpath $BIDS`

#------------------------------------------------------------------------------#
#    PACKAGES DEPENDENCIES print versions
# others
if [[ -z `which dcm2niix` ]]; then Error "Check your dcm2niix installation"; exit 0; else Info "dcm2niix was found"; fi
if [[ -z `which tree` ]]; then Warn "tree function was not found"; fi
#  MRtrix3 - NOTE dwifslpreproc is from MRtrix 3.0.0, we have 3.0_RC3-178-g32afe60f
#if [[ -z `which dwifslpreproc` ]]; then Error "MRtrix3 was not found"; exit 0; else Info "MRtrix3 version: `dwifslpreproc -version | awk 'NR==1 {print $3}'`"; fi
if [[ -z `which mrconvert` ]]; then Error "MRtrix3 was not found"; exit 0; else Info "MRtrix3 version: `mrconvert -version | awk 'NR==1 {print $3}'`"; fi
# freesurfer
if [[ -z `which recon-all` ]]; then Error "FreeSurfer was not found"; exit 0; else Info "FreeSurfer version: `recon-all -version`"; fi
# FSL
if [[ -z `which flirt` ]]; then Error "FSL was not found"; exit 0; else Info "FSL version: `flirt -version | awk '{print $3}'`"; fi
# AFNI
if [[ -z `which 3dresample` ]]; then Error "AFNI was not found"; exit 0; else Info "AFNI version: `afni -version | awk -F ':' '{print $1}'`"; fi
# ANTSx
if [[ -z "${ANTSPATH}" ]]; then Error "ANTs was not found"; exit 0; else Info "ANTS binaries: $ANTSPATH"; fi
# Minc tool kit
# Won't use minc tools in this release
#if [[ -z `which mincgen` ]]; then Warning "Minc Tool Kit was not found, proceed with caution"; else Info "Minc version: `mincgen -version | awk 'NR==1{print $2}'`"; fi

# LOADS variables with the BIDS format
bids_variables $BIDS $id $out

# Directories check
if [[ ${force} == TRUE ]]; then
  Warning "$id processing directory will be overwritten"
  rm -rf $out/${subject};
fi
if [ -d ${subject_dir} ]; then Warning "Output directory already exist, processing will continue.\n\t\t If you want to re-run everything use -force to overwrite it. \n\t\t ${subject_dir}"; fi
if [ ! -d ${subject_bids} ]; then Error "$id was not found on the BIDS directory\n\t     ${subject_bids}"; exit 0; fi

#------------------------------------------------------------------------------#
#			  Timer & Beginning
aloita=$(date +%s)

#------------------------------------------------------------------------------#
#   Define directories
#
##  TEMPORAL arguments: utilities should be sourced from an open repository
scriptDir=${MICASOFT_DIR}/pipelines/08_micaProcessing
bids_scripts=${MICASOFT_DIR}/pipelines/09_bids_micaProcessing
# # MUST CHANGE: THESE files should be source from an open repository:
# volumeTemplateDirectory
# REQUEST: move utilities to an open Directory
export util_MNIvolumes=${scriptDir}/utilities/MNI152Volumes
# parcDirectory
export util_parcelations=${scriptDir}/utilities/parcellations
export util_surface=${scriptDir}/utilities/resample_fsaverage

# Creates subject directory if it doesn't exist
if [ ! -d ${subject_dir} ]; then
    Info "Subject ${id} directory doesn't exist"
    Do_cmd mkdir -p $subject_dir/{logs,xfms,unassigned,proc_dwi,proc_struct/{first,volumetric,surfpatch,surfaces/{conte69,$subject}}}
else
    Info "Subject ${id} directory exist"
fi

# print directory  organization
if [[ ! -z `which tree` ]]; then Info "$subject directory structure:\n"; tree -d $subject_dir; fi

#------------------------------------------------------------------------------#
# # # MICA - WORKSTATION  Structural processing: Volumetric
if [ "$proc" = "TRUE" ] || [ "$proc1" = "TRUE" ]; then
    mmTemplates="0.8 2" ### MNI152 templates resolutions
    t1Scans=$(find $subject_bids/anat/ -name "*ses-pre_run-?_T1w.nii.gz" )
    t1ScansCmd=$(echo "-t $(echo $t1Scans | sed 's: : -t :g')")
    # ------------------------------------------------------------------------------#
    if [[ $micaq == "TRUE" ]] ; then
      Warning "This option only works on the MICA workstations, for now..."
      Warning "This step uses NUC and CLAMP, for now..."
      if [[ -z $(mica_qget names . . "*" | grep ${id}_structuralVolumetric) ]] ; then
          rm -fv $dir_logs/structuralVolumetric.txt
          qsub \
              -q mica.q \
              -l h_vmem=6G \
              -N ${id}_structuralVolumetric \
              -e $dir_logs/structuralVolumetric.txt \
              -o $dir_logs/structuralVolumetric.txt \
              -hold_jid ${id}_dicom2bids \
              $bids_scripts/01_proc-struc_volumetric-MTL.sh \
              -n -p SETDEFAULT $t1ScansCmd \
              "0.8 2" \
              $proc_struct \
              $dir_warp \
              $util_MNIvolumes \
              $dir_first \
              $id
      fi
    else
      # ------------------------------------------------------------------------------#
      #   Structural processing: Volumetric
      # the $4 argument is the tmp directory where processes will run default is /tmp
      01_proc-struc_volumetric.sh $BIDS $id $out  2>&1 | tee ${dir_logs}/proc_freesurfer.txt
    fi
fi

# ##------------------------------------------------------------------------------#
# # # MICA - WORKSTATION  Structural processing: Freesurfer
if [ "$proc" = "TRUE" ] || [ "$proc2" = "TRUE" ]; then
    Title "Running structural processing: Freesurfer"
    # SGE -qsub TRUE
    if [[ $micaq == "TRUE" ]] ; then
      Warning "Setting a warper to run on mica.q"
    else
      # ------------------------------------------------------------------------------#
      #  Structural processing: Freesurfer
      # the $4 argument is the tmp directory where processes will run default is /tmp
       01_proc-struc_freesurfer.sh $BIDS $id $out 2>&1 | tee ${dir_logs}/proc_volumetric.txt
    fi
fi


# ##------------------------------------------------------------------------------#
# # # MICA - WORKSTATION  POST Structural processing
if [ "$proc" = "TRUE" ] || [ "$post1" = "TRUE" ]; then
    Title "Running POST structural processing: Surfaces and parcellations"
    # SGE -qsub TRUE
    if [[ $micaq == "TRUE" ]] ; then
      Warning "Setting a warper to run on mica.q"
    else
      # ------------------------------------------------------------------------------#
      #  POST-Structural processing
      # the $4 argument is the tmp directory where processes will run default is /tmp
       02_post-structural.sh $BIDS $id $out 2>&1 | tee ${dir_logs}/post_structural.txt
    fi
fi


# ##------------------------------------------------------------------------------#
# # # MICA - WORKSTATION  Diffusion processing
# ------------------------------------------------------------------------------#
#  Diffusion processing


# ##------------------------------------------------------------------------------#
# # # MICA - WORKSTATION  Resting state
# ------------------------------------------------------------------------------#
#  Resting state


##------------------------------------------------------------------------------#
#			 Total Running Time
lopuu=$(date +%s)
eri=$(echo "$lopuu - $aloita" | bc)
eri=`echo print $eri/60 | perl`

Title "TOTAL running time:\033[38;5;220m `printf "%0.3f\n" ${eri}` minutes \033[38;5;141m"
